### ISSUE TITLE
separate trigger for visible prop

### ISSUE THREAD

**Issue by immigration9** [atomiks/tippyjs-react#165]
While developing with tippy react, I noticed that there aren't any triggers available when `visible` prop is passed to the component.

```javascript
const [visible, setVisible] = useState(true);

return (
    <Tooltip
      content={<div onClick={hideTooltip}>{content}</div>}
      visible={visible}
      interactive
      hideOnClick={false}
    >
      <div onClick={hideTooltip}>{children}</div>
    </Tooltip>
  );
```

in this case, I wanted to hide tooltip + do other things (eg. set local storage) so I made another wrapper for the children component, but was wondering if there could be any trigger for detecting events when visible state is passed.

it might look something like this
```javascript
const [visible, setVisible] = useState(true);

return (
    <Tooltip
      content={<div onClick={hideTooltip}>{content}</div>}
      visible={visible}
      interactive
      hideOnClick={false}
      onChildTrigger={(inst, evt) => hideTooltip()}
    >
      {children}
    </Tooltip>
  );
```

Thanks.

**Comment by atomiks** [comment]
`visible` puts the Tippy in controlled mode, so you need to use React's state and events to control the Tippy.
