### ISSUE TITLE
Nested tooltip position change on state change

### ISSUE THREAD

**Issue by Arkellys** [atomiks/tippyjs-react#177]
I just updated my version of tippy to the latest release (`4.0.0-alpha.1`) and came across an issue with nested tooltips. If a state in the component changes while the nested tooltip is open, its position also changes.

CodeSandbox: https://codesandbox.io/s/inspiring-engelbart-iqqmp

**Comment by atomiks** [comment]
So this was tricky to debug... it's an async problem. 

In the new version we destroy + create the popperInstance on updates without any dependency checks, and the nested instance gets created before the parent one — in this case, the parent popper has been destroyed with no styles applied yet, so the nested one gets positioned as though the parent popper is at the topleft of its offsetParent, not where it will be right after the nested one gets positioned.

Adding a `instance.popperInstance?.forceUpdate()` right after `.setProps()` solves it but then we have two updates which isn't the best for efficiency 🤔, maybe there's a cleaner solution

**Comment by atomiks** [comment]
This should be fixed in the latest version. It occurred in the previous major as well, just more rarely due to the dep checks I believe.

**Comment by Arkellys** [comment]
Amazing, the speed with which you solve problems never ceases to amaze me! Thank you again.

**Comment by zhaoyao91** [comment]
has this issue already been fixed? I encountered similar problem in v4.0.2.

![Kapture 2020-06-04 at 20 00 57](https://user-images.githubusercontent.com/3808838/83754904-51c38380-a69f-11ea-96e7-b5352179e43a.gif)

**Comment by zhaoyao91** [comment]
> So this was tricky to debug... it's an async problem.
> 
> In the new version we destroy + create the popperInstance on updates without any dependency checks, and the nested instance gets created before the parent one — in this case, the parent popper has been destroyed with no styles applied yet, so the nested one gets positioned as though the parent popper is at the topleft of its offsetParent, not where it will be right after the nested one gets positioned.
> 
> Adding a `instance.popperInstance?.forceUpdate()` right after `.setProps()` solves it but then we have two updates which isn't the best for efficiency 🤔, maybe there's a cleaner solution

I've tried this method, but it resulted in flicker of the position.

**Comment by atomiks** [comment]
It shouldn't occur in the latest, you'll need to create a repro for investigation

**Comment by zhaoyao91** [comment]
The items with tooltip are inside a [scrollbar](https://kingsora.github.io/OverlayScrollbars/#!overview) section, and this section is inside a popover. Is the existing of scrollbar breaking the logic of nested pop?
