### ISSUE TITLE
onHide firing on unmount

### ISSUE THREAD

**Issue by mraymond** [atomiks/tippyjs-react#179]
Currently the onHide event is firing when you unmount as shown in the codesandbox below when clicking the 'Un/mount' button. This causes issues when we need something to happen on hide of the tooltip vs unmounting. The work around we had to implement for this was in our wrapper around tippy we have a visible state that we check against before calling our onHide.

And if this is correct behavior, should onShow be firing on mount?

https://codesandbox.io/s/agitated-bhaskara-vv70y

**Comment by atomiks** [comment]
It looks like this is fixed in latest https://codesandbox.io/s/intelligent-microservice-qlm9k

**Comment by mraymond** [comment]
Sorry about that, just some weird wording. But the issue that you see fixed in the latest solves our problem. Thanks for looking into it.
