### ISSUE TITLE
Destructing props object isn't working since v6

### ISSUE THREAD

**Issue by JamesJGoodwin** [atomiks/tippyjs-react#180]
Hello. I've moved to Tippy v6 today and I'm a bit confused because destructing props are no longer available. In v5 I had this code:

```tsx
import Tippy from '@tippy.js/react'
import { Props as TippyOptions } from 'tippy.js'

// this code is ok, no errors (I changed the options according to v6 documentation in this code snippet to check whether any errors are throwing)
const tooltipConfig: Partial<TippyOptions> = {
    delay: 0,
    duration: [300, 150],
    inertia: true,
    animation: 'shift-away',
    arrow: roundArrow,
    interactive: true,
    trigger: 'click',
    theme: 'light currency_selector',
    placement: 'bottom',
    popperOptions: {
        modifiers: [
            {
                name: 'flip',
                enabled: true
            },
            {
                name: 'computeStyles',
                options: {
                    gpuAcceleration: false // true by default
                }
            }
        ]
    }
}

// somewhere else in my code

    return (
        <Tippy // <--- error goes there in v6
            {...tooltipConfig}
            appendTo={document.body}
            content={<CurrencyList onCurrencyChange={onCurrencyChange} />}
            onCreate={(instance: TippyInstance): TippyInstance<TippyOptions> => (tippyInstance.current = instance)}
        >
            <div className="current-currency">
                <span className="label">{currencies[currency].label}</span>
                <i className="fas fa-angle-down"></i>
            </div>
        </Tippy>
    )
```

If I try to do so in v6, VS Code will underline opening `<Tippy>` tag and show an error:

>Type '{ children: Element; appendTo: HTMLElement; content: Element; onCreate: (instance: Instance<Props>) => Instance<Props>; ... 41 more ...; zIndex?: number; }' is not assignable to type 'TippyProps'.
  Types of property 'render' are incompatible.
    Type '(instance: Instance<Props>) => { popper: PopperElement<Props>; onUpdate?: (prevProps: Props, nextProps: Props) => void; }' is not assignable to type '(attrs: { 'data-placement': Placement; 'data-reference-hidden'?: string; 'data-escaped'?: string; }, content?: Content) => ReactNode'.
      Types of parameters 'instance' and 'attrs' are incompatible.
        Type '{ 'data-placement': Placement; 'data-reference-hidden'?: string; 'data-escaped'?: string; }' is missing the following properties from type 'Instance<Props>': clearDelayTimeouts, destroy, disable, enable, and 12 more.ts(2322)

This is something that is really hard to read and especially to understand but I managed to resolve it randomly by commenting out `{...tooltipConfig}`. Also if I move all options from a JS-variable to JSX-props it will work as well.

**Comment by atomiks** [comment]
It's just a TypeScript error. The `render` prop in Tippy React is different to Tippy Core. You need to use `TippyProps` interface exported from `@tippyjs/react` intead of core's `Props`, I think.

**Comment by atomiks** [comment]
Also, your package is `@tippy.js/react` which is deprecated, the new package is `@tippyjs/react` (without a dot)

**Comment by JamesJGoodwin** [comment]
>Also, your package is @tippy.js/react which is deprecated
Yeah, I mentioned this as well in the middle of creation of this issue. I was using the new package, just forgot to change it in snippet.

Nevertheless, changing `Options` to `TippyProps` resolved the issue, thanks.

From repo README:
>This is a lightweight wrapper that lets you use it declaratively in React.

If my memory is not cheating on me, `@tippy[dot].js/react` was a wrapper as well since core types where compatible with it's React version. In `@tippyjs/react` types are a bit different and incompatible with core's. So maybe it is worth mentioning for those who's moving from a deprecated version?

**Comment by atomiks** [comment]
`content` wasn't compatible either I think. The only difference now is `render` isn't compatible (although that wasn't a thing in v5): https://github.com/atomiks/tippyjs-react/blob/e291b00eb5f95be6487ce243710439cca07fda01/index.d.ts#L12
