### ISSUE TITLE
Advice on dynamic tooltips

### ISSUE THREAD

**Issue by AndrewRSharp** [atomiks/tippyjs-react#181]
Apologies if this is answered elsewhere, but I couldn't find it. I'm trying to switch from react-tippy to this library, but am having a couple of issues recreating the same behavior and am hoping you can guide me. I have a list of items from a database that I build my tooltips on dynamically. The tooltips themselves then go out and get more information for display. This worked previously, though there were other shortcomings like placement never seemed to work for me until switching to this library, but now I'm having two main issues:
1) It seems that all tooltips are being created and rendered behind the scenes rather than one at a time when I hover over the item. My list could be very long and I'd rather not make unnecessary network calls if the user is only going to hover over one or two items in the list.
2) I can't seem to find an example of, or hack my way into, a tooltip that will either wait for everything to resolve (since I guess it's prerendered?) or update the content. I also can't seem to get setContent to work. Are there any examples of this you can point me to?

Thanks.

**Comment by CarlosLevir** [comment]
@AndrewRSharp Here is the that used to fix this problem:
```js
const [activatedContainer, setActivatedContainer] = useState();

const EmojiPicker = useCallback(
  (messageId) => {
    return activatedContainer !== messageId ? (
      <div />
    ) : (
      <NimblePicker
        set="twitter"
        data={emojiData}
        showPreview={false}
        showSkinTones={false}
        enableFrequentEmojiSort
        autoFocus
        color="#7159c1"
        emojiSize={24}
        sheetSize={32}
        perLine={10}
        onSelect={(emoji) => handleEmoji(emoji, messageId)}
        i18n={emojiI18n}
      />
    );
  },
  [emojiI18n, handleEmoji, activatedContainer]
);
```

And in the Tippy:

```js
<Tippy
  animation="shift-away"
  arrow={false}
  content={EmojiPicker(_id)}
  distance={24}
  inertia
  interactive
  theme="transparent"
  trigger="click"
  offset={-140}
  ref={emojiRef}
  onShow={handleSetActivatedContainer(_id)}
  onHide={handleSetActivatedContainer()}
>
  <button
    type="button"
  >
  Open picker
  </button>
</Tippy>
```

Basically, I set a value in state to check what container was click, and I compare it and return only a div if that container wasn't clicked.

I hope it helps you.

**Comment by atomiks** [comment]
^yep, you defer rendering the content by using `onShow` / `onHide`

Simplified version:

```jsx
const [visible, setVisible] = useState(false);

<Tippy
  content={visible ? expensiveContent : ''}
  onShow={() => setVisible(true)} 
  onHide={() => setVisible(false)}
/>
```

**Comment by AndrewRSharp** [comment]
Thank you both, this led me down the path to get my tooltips working!
