### ISSUE TITLE
Set global default props

### ISSUE THREAD

**Issue by rontav** [atomiks/tippyjs-react#182]
Is there a way to use `tippy.setDefaultProps` or otherwise set default props for all Tippy components?
Using `tippy.setDefaultProps` doesn't seem to influence react components.
One option could be creating a proxy component, but that breaks props autocompletion for VSCode.

**Comment by atomiks** [comment]
> One option could be creating a proxy component, but that breaks props autocompletion for VSCode.

Doesn't this work?:

```ts
const TippyProxy: React.FC<TippyProps> = (...) => {}
```

**Comment by rontav** [comment]
Yeah, it would work, but I don't have typescript support in my project.

**Comment by atomiks** [comment]
`tippy.setDefaultProps({})` is working for me with the latest version 🤔

**Comment by atomiks** [comment]
Repro: https://codesandbox.io/s/pensive-bhabha-s7n4s

Make sure you're importing `Tippy` from a central local module/file and only calling `setDefaultProps` once in that module, that might be the issue.

**Comment by rontav** [comment]
I should've done this from the start, but here's what I want to do: [https://codesandbox.io/s/heuristic-herschel-71kwh](https://codesandbox.io/s/heuristic-herschel-71kwh). As you can see, I've tried using tippy without react and the output is the same. Maybe this issue should be moved to [tippyjs](https://github.com/atomiks/tippyjs/issues).

From what I get by reading the source code of tippy, this should be a supported use case.
