### ISSUE TITLE
v4 stable

### ISSUE THREAD

**Issue by KubaJastrz** [atomiks/tippyjs-react#183]
I see that @tippyjs/react is still in [4.0.0-alpha.4](https://github.com/atomiks/tippyjs-react/blob/e291b00eb5f95be6487ce243710439cca07fda01/package.json#L3). What is still missing for a stable v4 release? Can I help in any way?

**Comment by atomiks** [comment]
There's some new APIs that I'm not certain of basically. It's almost completely stable really but I'd like to continue to break some small things if necessary 👀

**Comment by KubaJastrz** [comment]
For me, tippy v6 is a major source of breaking changes already. Integrating it within a large codebase will probably take me a while, even though I try to maintain good abstractions.

But if you feel like it's not ready then no pressure :sweat_smile:

**Comment by atomiks** [comment]
> tippy v6 is a major source of breaking changes already.

Which are the most painful? Does the migration guide help?

**Comment by KubaJastrz** [comment]
Mostly popper-related stuff. Migration guide seems fine, but you never know when you'll encounter issues.

**Comment by atomiks** [comment]
Okay so... there haven't been any issues filed for v4 yet and it's over a month old. I think the APIs work. I'll do a final release this weekend

**Comment by atomiks** [comment]
I released it 😇
