### ISSUE TITLE
Integrating with `framer-motion`

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippyjs-react#186]
It looks like `framer-motion` offers a purely declarative API for animations. `react-spring` can be used imperatively which can integrate with Tippy using its lifecycle hooks (shown on the docs).

How can we make this wrapper work with `framer-motion`? It's growing in popularity and generally users will only be using a single animation library... if it exported an imperative `spring` function that would help.

**Comment by atomiks** [comment]
So it's possible just like with `react-spring` using `useSpring`, I've added it to the docs.

One remaining problem: how to springify the popper's moves on position updates (spring version of `moveTransition`) using these two libraries, since we internally mutate that and don't allow headless rendering of the root popper node...

**Comment by atomiks** [comment]
> how to springify the popper's moves on position updates (spring version of moveTransition) 

https://codesandbox.io/s/tippyjs-react-framer-motion-j94mj

**Comment by i-am-the-slime** [comment]
Is this still the best way? No declarative option?
