### ISSUE TITLE
Positioning only on one axis?

### ISSUE THREAD

**Issue by osdiab** [atomiks/tippyjs-react#188]
I am unsure if I'm using the library wrong. It seems that the tooltip is only being positioned along a single axis instead of along both. I've tried this with both the Headless and default versions of React Tippy (`4.0.0-alpha-4`) but no cigar.

I am making a wrapper around the tooltip as so:

```tsx
/** @jsx jsx */
import { jsx } from "@emotion/core";
import css from "@emotion/css/macro";
import styled from "@emotion/styled/macro";
import Tippy, { TippyProps } from "@tippyjs/react/headless";
import React from "react";

import { colorCssVars } from "@app/theme/colorTheme";
import { spacing } from "@app/theme/spacing";

export interface PopoverProps extends TippyProps {}

const ARROW_WIDTH = "16px";
const ARROW_HEIGHT = "8px";
const Arrow = styled.svg`
  display: block;
  width: ${ARROW_WIDTH};
  height: ${ARROW_HEIGHT};
  path {
    stroke: var(${colorCssVars.text.secondary});
    stroke-width: 1px;
    fill: var(${colorCssVars.background.normal});
  }
`;

const Box = styled.div`
  padding: ${spacing.s};
  border: 1px solid var(${colorCssVars.text.secondary});
  border-radius: 3px;

  > ${Arrow} {
    position: absolute;
  }
  &[data-placement^="bottom"] > ${Arrow} {
    top: calc(1px - ${ARROW_HEIGHT});
  }
  &[data-placement^="right"] > ${Arrow} {
    transform: rotate(-90deg);
    left: calc(1px - ${ARROW_HEIGHT} - (${ARROW_WIDTH} - ${ARROW_HEIGHT}) / 2);
  }
  &[data-placement^="left"] > ${Arrow} {
    transform: rotate(90deg);
    right: calc(1px - ${ARROW_HEIGHT} - (${ARROW_WIDTH} - ${ARROW_HEIGHT}) / 2);
  }
  &[data-placement^="top"] > ${Arrow} {
    transform: rotate(180deg);
    bottom: calc(1px - ${ARROW_HEIGHT});
  }
`;

/**
 * Wrapper around tippy for consistent styles
 */
export const Popover: React.FC<PopoverProps> = ({ content, ...rest }) => (
  <Tippy
    render={attrs => (
      <Box {...attrs}>
        {content}
        <Arrow
          data-popper-arrow=""
          viewBox="0 0 21 11"
          width="20px"
          height="10px"
        >
          <path d="M0,11 L9.43630703,1.0733987 L9.43630703,1.0733987 C10.1266203,0.3284971 11.2459708,0 11.936284,1.0733987 L20,11" />
        </Arrow>
      </Box>
    )}
    {...rest}
  />
);
```

But when I try to use it in my storybook, it seems to only calculate positions along one of the two axes, and also fails to position my arrow properly in the box:

```tsx
/** @jsx jsx */
import { jsx } from "@emotion/core";
import css from "@emotion/css/macro";
import { placements } from "@popperjs/core/lib/enums";
import { withKnobs, select } from "@storybook/addon-knobs";
import { Placement } from "tippy.js";

import { Popover, PopoverProps } from "@app/components/common/Popover";

export default {
  title: "Popover",
  component: Popover,
  decorators: [withKnobs]
};

enum PopoverVisibility {
  SHOW = "Show",
  HIDE = "Hide",
  UNCONTROLLED = "Uncontrolled"
}
const VISIBLE_PROP_VALUE: {
  [key in PopoverVisibility]: PopoverProps["visible"];
} = {
  [PopoverVisibility.SHOW]: true,
  [PopoverVisibility.HIDE]: false,
  [PopoverVisibility.UNCONTROLLED]: undefined
};

const placementOptions = Object.fromEntries(placements.map(p => [p, p]));
export const Basic = () => {
  return (
    <main
      css={css`
        width: 100%;
        height: 300px;
        display: flex;
        justify-content: center;
        align-items: center;
      `}
    >
      <Popover
        content={"Popover content"}
        placement={select<Placement>("Placement", placementOptions, "auto")}
        visible={
          VISIBLE_PROP_VALUE[
            select<PopoverVisibility>(
              "Visibility",
              PopoverVisibility,
              PopoverVisibility.UNCONTROLLED
            )
          ]
        }
      >
        <b css={{ flexGrow: 0 }}>Popover on this element</b>
      </Popover>
    </main>
  );
};
```

That results in this output:

<img width="1065" alt="Screen Shot 2020-04-06 at 17 28 51" src="https://user-images.githubusercontent.com/1890926/78538877-a926ae00-782c-11ea-98a2-8a9dc9245639.png">
<img width="1074" alt="Screen Shot 2020-04-06 at 17 28 58" src="https://user-images.githubusercontent.com/1890926/78538898-afb52580-782c-11ea-84ef-905dce94918d.png">
<img width="1074" alt="Screen Shot 2020-04-06 at 17 29 06" src="https://user-images.githubusercontent.com/1890926/78538900-b0e65280-782c-11ea-9d06-c779d7c24282.png">
<img width="1079" alt="Screen Shot 2020-04-06 at 17 29 11" src="https://user-images.githubusercontent.com/1890926/78538904-b17ee900-782c-11ea-9e9d-f5dd693d10bc.png">

When I look at the inspector, I notice two things:

1. the `translate3d` value for the tippy element is only being set on one of the axes:

<img width="606" alt="Screen Shot 2020-04-06 at 17 39 28" src="https://user-images.githubusercontent.com/1890926/78539562-ba23ef00-782d-11ea-8773-71c6a8425e01.png">

1. the `data-popper-arrow` element only has my positioning + the library seems to be setting `position: absolute` with no actual coordinates to place it properly relative to the element:

<img width="592" alt="Screen Shot 2020-04-06 at 17 39 45" src="https://user-images.githubusercontent.com/1890926/78539622-d2940980-782d-11ea-8e67-4bd4cd5cf437.png">

This is where the element to place the tooltip against is being positioned on the page:

<img width="939" alt="Screen Shot 2020-04-06 at 17 44 58" src="https://user-images.githubusercontent.com/1890926/78539964-5fd75e00-782e-11ea-8ff3-917272e1cca1.png">

Am I using this library wrong? It's odd to me that the `translate3d` value applied to the tippy element is only setting one of the axes, leaving the other one as `0`. Thanks!

**Comment by atomiks** [comment]
I think it's the `flex` container actually. Does `appendTo={document.body}` work?

**Comment by atomiks** [comment]
Okay yeah I just reproduced it. Wrapping the `<svg>` in a `<div>` (which has `data-popper-arrow` instead of the `<svg>`) fixes the issue. The arrow must be an `HTMLElement`.
