### ISSUE TITLE
Should `tippy.js` be a peer dependency?

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippyjs-react#190]
`react-popper@2` does this now with `@popperjs/core`. Also, when using Default Tippy, the user often specifies `tippy.js/*` paths to import. I think it should be an explicit dependency.

/cc @FezVrasta @KubaJastrz

**Comment by KubaJastrz** [comment]
I don't really like the concept of peer dependencies. As a user, you shouldn't need to know about underlying code that is used in the end product. 

I'd rather re-export everything from tippy core in react tippy.

**Comment by atomiks** [comment]
Problem with re-exporting is you need to update once the dependency also updates for new exports. Also, CSS stylesheets, etc. If you manage the `tippy.js` version yourself it becomes more obvious when features/patches are available

**Comment by KubaJastrz** [comment]
Yeah, I guess we have a lot of stuff hidden in dist files. Maybe if we were using a monorepo it would be easier to do.

**Comment by atomiks** [comment]
I'm leaving it as a dep after discussing with @FezVrasta due to the fact that we have a `@popperjs/core` dependency too, things could get messy if people wanted multiple peer deps etc. As far as I can tell you can update every dep to latest with a simple command `npm i @tippyjs/react@latest`. It doesn't require knowing implementation details of packages.
