### ISSUE TITLE
All Tippy props are marked as required

### ISSUE THREAD

**Issue by itayganor** [atomiks/tippyjs-react#191]
Hi there,

When I use `<Tippy>` in my Typescript project, it looks like it expects to get a huge amount of props:
![image](https://user-images.githubusercontent.com/6430313/79069043-dd3e1b00-7cd3-11ea-84b5-91f42957c1d7.png)

Moreover, when using the autocomplete option for components, this is what happens:
![tippy](https://user-images.githubusercontent.com/6430313/79069082-12e30400-7cd4-11ea-98bf-a8d55732fa30.gif)

(using Webstorm)

**Comment by KubaJastrz** [comment]
Which version of tippy react are you using?

**Comment by itayganor** [comment]
> Which version of tippy react are you using?

`^4.0.0-alpha.4`

**Comment by KubaJastrz** [comment]
Doesn't happen to me in [codesandbox](https://codesandbox.io/s/brave-bouman-euxuh?file=/src/App.tsx).

Also, [all props are optional by default](https://github.com/atomiks/tippyjs-react/blob/v4.0.0-alpha.4/index.d.ts#L12-L30) and the `TippyProps` extends from `Partial<Props>` so there is no way that anything is required.

Seems like an error in configuration maybe? Can you post a minimal example with your `tsconfig.json`?

**Comment by itayganor** [comment]
Sure, there it is. I stripped down some unrelated parts.

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "outDir": "./dist/",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "noImplicitAny": false,
    "jsx": "react",
    "allowJs": true,
    "moduleResolution": "node",
    "baseUrl": "."
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "include": [
    "./src/**/*",
    "./src/declarations.d.ts"
  ]
}
```

**Comment by KubaJastrz** [comment]
I downloaded a fresh install of Webstorm and was able to reproduce it using my codesandbox example and your tsconfig.json.

I'll investigate further and will get back to you.

**Comment by KubaJastrz** [comment]
@itayganor, it seems like the issue occurs only on Webstorm IDE. I can't reproduce it on VSCode or CodeSandbox.

I can see that Webstorm has had [similar issues](https://youtrack.jetbrains.com/issues?q=jsx%20element%20doesn%27t%20have%20required%20element) in the past, so you can ask for help on JetBrains issue tracker. You can link to my codesandbox example for reproduction code if needed. Good luck!

**Comment by atomiks** [comment]
Is it due to `Omit` maybe? It's a relatively new TS feature

But yeah there isn't anything wrong with the TS, sadly looks like a Webstorm issue. If there is something we can do to workaround it please send a PR.

**Comment by KubaJastrz** [comment]
> Is it due to Omit maybe? It's a relatively new TS feature

I doubt. `Omit` is using a combination of `Pick` and `Exclude` which were already present before. And by default, Webstorm is using local version of TS (3.7.5), which in this case supports `Omit` (added in 3.5).

**Comment by atomiks** [comment]
I just downloaded Webstorm on Mac and the issue doesn't happen 🤔 maybe a Windows thing?

**Comment by wahlstedt** [comment]
FYI This still happens in IntelliJ IDEA Ultimate 2020.1 (on Mac)

**Comment by atomiks** [comment]
Tell IntelliJ to fix their buggy software lol?

**Comment by itayganor** [comment]
@atomiks 
Looking at `Props` defined in [tippy.js's `src/types.ts:65`](https://github.com/atomiks/tippyjs/blob/master/src/types.ts#L65), All properties are marked as required. Is this intentional?

**Comment by atomiks** [comment]
Yes, but it shouldn't matter because we use `Partial<Props>` in [`index.d.ts`](https://github.com/atomiks/tippyjs-react/blob/c048bf4c62d42026d907973ee2e9c73b74d41301/index.d.ts#L12) as @KubaJastrz mentioned. 

The only thing I can suggest is dig into `node_modules/@tippyjs/react/index.d.ts` and mess around with `TippyProps` (as in, remove `Omit`, try un-inlining `Partial<Props>`, etc.) interface to get it to work.

**Comment by Lynith1** [comment]
@atomiks  I noticed if I made it Partial<Omit<Props, 'content' | 'renderer'>> Webstorm seemed to handle it properly and the errors went away.  

There shouldn't be a difference between the two implementations, yeah?
Props -> Make all Optional -> Omit content and renderer
Props -> Omit content and renderer -> Make all Optional

Only problem is every time I update, it's going to undo that change.

**Comment by atomiks** [comment]
> Only problem is every time I update, it's going to undo that change.

Not if you submit a PR to fix it 😛

**Comment by Lynith1** [comment]
I'm fairly new to this.  I didn't know if it would mess something else up.
Will do

**Comment by atomiks** [comment]
@Lynith1 okay don't worry then, I'll just do it
