### ISSUE TITLE
Unnecessary `forwardRef`on `Tippy` component?

### ISSUE THREAD

**Issue by KubaJastrz** [atomiks/tippyjs-react#192]
@atomiks, why are we using `forwardRef` on `TippyGenerator`?

https://github.com/atomiks/tippyjs-react/blob/1c1cd281897086430c6b15c422e4309801081e03/src/index.js#L8

I doesn't look like the `Tippy` components is accepting second `ref` parameter that is passed from `forwardRef`.

https://github.com/atomiks/tippyjs-react/blob/1c1cd281897086430c6b15c422e4309801081e03/src/Tippy.js#L14-L29

If we don't need it, we could simplify `Tippy` to `React.FunctionComponent<TippyProps>`

https://github.com/atomiks/tippyjs-react/blob/1c1cd281897086430c6b15c422e4309801081e03/index.d.ts#L29

**Comment by atomiks** [comment]
It's required for nesting the components

**Comment by KubaJastrz** [comment]
Ah, sorry. I didn't notice that this `forwardRef` is a wrapper for React's `forwardRef`: https://github.com/atomiks/tippyjs-react/blob/1c1cd281897086430c6b15c422e4309801081e03/src/index.js#L8
