### ISSUE TITLE
forwardRef with changing children components

### ISSUE THREAD

**Issue by elya158** [atomiks/tippyjs-react#194]
I have a component that wraps Tippy called **Tooltip** in my app. How is it possible to implement ref forwarding when different child components can be passed? (Note that using a span tag instead of forwardRef, to wrap `{ children }` breaks the css design)

This is how **Tooltip** basically looks:
```
const Tooltip = ({ options, content, children }) => {
  const tippyProps = omit(extend({}, DEFAULT_TIPPY_OPTIONS, options), ['content', 'children']);
  const hideAllTooltips = (instance) => {
    hideAll({ duration: 0 });
    if (tippyProps.onShow) tippyProps.onShow(instance);
  };

  return (
    !content ? children :
      <Tippy
        content={ content } { ...tippyProps } onShow={ hideAllTooltips }>
        { children }
      </Tippy>
  );
};
```

I have a bunch of usages and it will be a pain adding forwardRef to each component that may be the child of **Tooltip**.
For example:
```
<Tooltip content="icon tooltip">
    <Icon />
</Tooltip>
```
```
<Tooltip content="checkbox tooltip">
    <Checkbox />
</Tooltip>
```

I have tried several things and I'm stuck, do you maybe have a solution for this?

**Comment by atomiks** [comment]
There isn't one; `forwardRef` is a temporary solution in React as `ref` will be part of `props` in the future, for now you need to do this for every component. `styled-components` does for example.

**Comment by shaunsaker** [comment]
@elya158 I'm not sure if this will help you but I ran into the same issue. You can wrap the `children` with a div and pass the ref to it instead:

```
import React, { ForwardedRef, forwardRef, ReactElement } from "react";
import Tippy from "@tippyjs/react";
import "tippy.js/dist/tippy.css";

type Children = ReactElement;

interface OnboardingCoachmarkProps {
  children: Children;
}

const ChildrenWithRef= forwardRef(
  ({ children }: { children: Children }, ref: ForwardedRef<HTMLDivElement>) => (
    <div ref={ref}>{children}</div>
  ),
);

export const OnboardingCoachmark = ({ children }: OnboardingCoachmarkProps) => {
  return (
    <Tippy content="HEY HEY HEY">
      <ChildrenWithRef>{children}</ChildrenWithRef>
    </Tippy>
  );
};

```
