### ISSUE TITLE
Singleton moveTransition

### ISSUE THREAD

**Issue by itayganor** [atomiks/tippyjs-react#195]
Hi!

`createSingleton` of the original `tippy.js` lets the user add custom transitions to the tooltip, so using singletons looks smooth as awesome.
Unfortunately `useSingleton` doesn't seem to receive a prop like that, and I couldn't find any way to mimic the result (except using `react-spring` and such).

Is there a way to achieve this?
Thanks!

**Comment by itayganor** [comment]
While digging into `useSingleton` implementation I found out it is derived from the singleton's source `<Tippy/>` element.

```react
<Tippy singleton={source} moveTransition="transform .2s ease-out"/>
```

**Comment by atomiks** [comment]
Yes, in v4, you use the `<Tippy />` component for singleton props. `useSingleton` only accepts two props: `disabled` and `overrides`.

**Comment by marcselman** [comment]
Thanks! Maybe add that to the documentation?
