### ISSUE TITLE
`interactiveBorder` prop seem to be ignored

### ISSUE THREAD

**Issue by zac-robinson** [atomiks/tippyjs-react#197]
I am attempting to use @tippyjs/react 4.0.0 and setting `interactiveBorder` doesn't seem like it is being applied?

Sandbox here: https://codesandbox.io/s/cocky-https-zjy6v?file=/src/App.js

**Comment by atomiks** [comment]
This is a problem of the `<body>` not stretching past the tippy (a `mouseleave` listener is set on it). See the styles.css here: https://codesandbox.io/s/priceless-lake-r7ejx?file=/src/styles.css

**Comment by zac-robinson** [comment]
👍
