### ISSUE TITLE
TypeScript can't find property 'interactive'

### ISSUE THREAD

**Issue by brucem1976** [atomiks/tippyjs-react#198]
When I try
```
<Tippy
  interactive={true}
  content={
  <a href=...>
    Test  
  </a>
  }
>
Hello
</Tippy>
```

I get:

> Type error: Type '{ children: Element; className: string; interactive: boolean; content: Element; }' is not assignable to type 'IntrinsicAttributes & TippyProps'.
>   Property 'interactive' does not exist on type 'IntrinsicAttributes & TippyProps'.

**Comment by KubaJastrz** [comment]
Hi, can you post more code? I can't reproduce on a simple example https://codesandbox.io/s/beautiful-montalcini-35xin?file=/src/App.tsx

**Comment by brucem1976** [comment]
Upgrading my TypeScript version from 3.2.2 to 3.7.5 fixed this thanks
