### ISSUE TITLE
Delay is applied individually to each Tippy sharing a single source singleton

### ISSUE THREAD

**Issue by Slapbox** [atomiks/tippyjs-react#201]
**Expected behavior:**

Once triggered, hovering other elements using the same singleton would immediately trigger the Tippy to show.

**Actual behavior:**

The chosen delay must be waited for each individual element

**Last known working:**

`v3.x`

**Current:**

`v4.0.1`

**Comment by atomiks** [comment]
Have you changed your callsites to match the new API? CodeSandbox demo would help

**Comment by Slapbox** [comment]
@atomiks thanks for the reply. I am very dumb. I did update for the new singleton properly... for half the toolbar.

Thanks for prompting me to look more carefully.
