### ISSUE TITLE
Feature request: Allow offset to be configured individually per Tippy within singleton

### ISSUE THREAD

**Issue by Slapbox** [atomiks/tippyjs-react#202]
## Problem

In a circumstance where we have a set of 4 buttons that visually appear identical, 1 of the 4 is constructed differently than the others and the tooltip for it doesn't align with the others. But the 4 are part of a single group and the behavior of `useSingleton` is highly desirable here. 

**DOM Structure:**
![image](https://user-images.githubusercontent.com/6835891/79671002-eaa44b00-8194-11ea-98c2-ab73bc74be9e.png)

And here's a recording of the sort of issue, for another set of buttons that similarly have one element that's not like the rest (different DOM setup though) https://recordit.co/8fcG0Uoyw2

## Solution

I know it goes against the design principles that seem to be in place in `v3` and up, but it would be very helpful to have offset configurable per-Tippy within a singleton without a crazy setup being required. 

In our app I've found 3 places this proves to be necessary in `v3` and `v4`, where it wasn't in `v2` (everything aligned properly), where it would have been easier to remedy if it had been an issue. I've found no situations where we needed to customize anything else on a per-Tippy basis like this, which makes me think it _might_ be worth supporting this. Not being able to set the offsets individually makes fighting the DOM much harder.

## Related issues

#153 - I tried to understand how to apply this to my current issue, but between the differences in syntax and the nature of the issue I'm getting a bit confused trying to conceptualize.

**Comment by atomiks** [comment]
This is natively supported now, just do:

```js
useSingleton({ overrides: ['offset'] });
```

**Comment by Slapbox** [comment]
That is a beautiful solution. Thank you so much!
