### ISSUE TITLE
One-off situation where placement -start/-start is always placed at -end instead

### ISSUE THREAD

**Issue by Slapbox** [atomiks/tippyjs-react#203]
Really not sure what to make of this one. I've tried to collect as much information as I can, but I don't think I've found enough to make the cause of this clear.

Nothing fancy here. There's no weird overflow situations, and the tooltip content is short enough to fit easily without any need for flipping, preventing overflow, anything else.

I've spent the past half hour fiddling with the DOM. I've gutted the problematic element and its styles. I raised the `<Tippy>` up one node at a time until I couldn't go any higher trying to find a clue, but nothing promising found. 

It obeys the `top` or `bottom` aspect, but not the `-start` part. The placement always aligns to `-end`.

![image](https://user-images.githubusercontent.com/6835891/79672800-19292280-81a3-11ea-9dbe-ac141e90ea9b.png)

```js
<UtilityItemRoot>
  <Tippy
    content={tipText}
    {...{
      placement: 'bottom-start',
      offset: [0, 8],
    }}>
    <Contents />
  </Tippy>
</UtilityItemRoot>
```

**Current version:** `@tippyjs/react@4.0.1`
**Last known working:** `@tippyjs/react@3.1.0`

**Comment by atomiks** [comment]
https://popper.js.org/docs/v2/modifiers/flip/#flipvariations?

**Comment by Slapbox** [comment]
Works! Thank you!

I don't really understand how/why though. I mean, I get what the option does, but if I place it to the right, the element extends beyond its parent without issue.

![image](https://user-images.githubusercontent.com/6835891/79673271-517e3000-81a6-11ea-9330-04bc014b975d.png)


 Is there any more information along these lines? https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-boundary

We were previously using that workaround, and dropped it as it no longer seemed necessary. If we still used it, would it theoretically have prevented this flipping behavior?

Thanks again for your patience and assistance (and incredible work!)
