### ISSUE TITLE
With useSingleton() className cannot be set

### ISSUE THREAD

**Issue by miracle2k** [atomiks/tippyjs-react#204]
See this example:

https://codesandbox.io/s/modest-fire-bfun4?file=/src/App.js

I can see that in the issue history there was work on this (e.g https://github.com/atomiks/tippyjs-react/pull/129) but I think it might have been lost.

**Comment by atomiks** [comment]
If you need a temp fix 

```jsx
<Tippy
  onCreate={instance => {
    instance.popper.firstElementChild.className = '...';
  }}
/>
```
