### ISSUE TITLE
Using updateDuration with the new useSingleton API

### ISSUE THREAD

**Issue by praneetrohida** [atomiks/tippyjs-react#205]
I am unable to figure out how to use the `updateDuration` prop with the new API. The tooltips look abrupt without it. It there a guide I am missing?

**Comment by atomiks** [comment]
https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-updateduration

Use an `easeOutQuint` `cubic-bezier` curve instead of the builtin `ease-out` though, but you can specify any easing function now and don't need to use the CSS.
