### ISSUE TITLE
Missing offset prop in type definitions

### ISSUE THREAD

**Issue by dpistoleKUBRA** [atomiks/tippyjs-react#206]
Our typescript linter was throwing the following error when trying to use the `offset` prop with a headless Tippy component.

```
Property 'offset' does not exist on type 'IntrinsicAttributes & TippyProps'
```

Seems like the typing gets defined [here](https://github.com/atomiks/tippyjs-react/blob/master/src/Tippy.js#L234), but that doesn't seem to cover the full list of allowed props [here](https://atomiks.github.io/tippyjs/v5/all-props/).

We've used TS ignore to disable the linting (shown below) but I wanted to pop this issue in case other run into it, or in case we're doing something wrong.

```
return (
    /*
    // @ts-ignore */
    <Tippy
      offset={offset}
      placement={placement}
      interactive={true}
      render={(attrs): any => (< ... />)}
    >
      {children}
    </Tippy>
  );
```

Appreciate your work on the library.

Thanks,
Don

**Comment by atomiks** [comment]
What are the versions of `@tippyjs/react` and `tippy.js`? Does it happen in an IDE or via CLI?

**Comment by dpistoleKUBRA** [comment]
Well that was a prompt response, thanks @atomiks 

Versions are as follows:
```
@tippyjs/react@4.0.2
tippy.js@6.2.2
```

We found the error when running our tests via CLI, using jest (w/ ts-jest to transform the test files)

**Comment by atomiks** [comment]
Here's where the `offset` type is defined: 

https://github.com/atomiks/tippyjs/blob/bf975605aa694e1cb1ad82e964b926830243ac80/src/types.ts#L83

Here's `TippyProps` (it extends that interface):

https://github.com/atomiks/tippyjs-react/blob/33efd52407a4f4bd9b126c12743b5f88fb155a3b/index.d.ts#L12

Any problems? Are you using the latest TS version and version of `ts-jest`?

**Comment by dpistoleKUBRA** [comment]
Ah I missed the extends bit, my bad. Updating typescript from `3.4.5` to `3.8.3` seems to have resolved it. If you've got a `buy atomiks a coffee` link or something please send it my way. Thanks again for your time, apologies for the false alarm.

Don

Don
