### ISSUE TITLE
How to use with Portals?

### ISSUE THREAD

**Issue by pleerock** [atomiks/tippyjs-react#207]
Broke my head trying to figure out how to use Tippy content in react portal.. Something like this isn't working:

```
<Tippy
      render={attrs => (
        <div {...attrs} onClick={() => setVisible(false)}>
          {ReactDOM.createPortal(
              props.content,
              document.getElementById("root-context-menu")!,
            )}
        </div>
      )}
...> button </Tippy>
```

because container with absolute positioning remains outside of portal. Wrapping Tippy into portal also won't work because I don't want button to be in the portal. Any hints? Thanks!

**Comment by atomiks** [comment]
What are you using the portal for? `<Tippy />` appends the content to the `<body />` by default, or you can specify where to put it via the `appendTo` prop.

```jsx
<Tippy
      render={attrs => (
        <div {...attrs} onClick={() => setVisible(false)}>
          {props.content}
        </div>
      )}
      appendTo={document.getElementById("root-context-menu")!}
> button </Tippy>
```

**Comment by pleerock** [comment]
> <Tippy /> appends the content to the <body /> by default

hmm, it doesn't... It appends into the place where its used in my case... That's why I wanted to use portals - to prevent styles inheritance. What can I do wrong that leads to my use-case?

**Comment by mhsattarian** [comment]
Hey, Sorry to open this issue again.
I ran to the same issue using an `interactive` tippy. it doesn't get appended to `body` by default.
although I must say adding `appendTo={document.body}` solved it.

**Comment by mhsattarian** [comment]
@atomiks

**Comment by spaciandd** [comment]
If anyone using in **nextjs**, then you need to create state for body, i.e.,

```
const [body, setBody] = useState(null);

useEffect(() => {
    setBody(document.body)
}, [])
```

then `appendTo={body}`

**Comment by 55Cancri** [comment]
these answers were amazing thank you guys so much
