### ISSUE TITLE
How to override default style and maintain positioning functionality

### ISSUE THREAD

**Issue by arianitu** [atomiks/tippyjs-react#208]
Hello, we're trying to use Tippy with styled-components, but the global tippy styles are overriding our styling such as adding a default black background box.

I know you mentioned in the latest release this would be fixed (https://github.com/atomiks/tippyjs-react/issues/168)

Can you help us understand what the best way to handle what we want to do:

1. We want to remove the black box and colours/padding etc.
2. We want to keep the fade animations
3. We want to keep the iOS positioning stuff you mentioned would be an issue if we didn't install the global.css

Can we just not include the global.css and have no position problems in the latest release?

**Comment by arianitu** [comment]
Oh sorry, one other thing I wanted to mention, because we are using `styled-components` we need to have a <div> or element returned instead of a React.Fragment.

I noticed the latest version returns a React.Fragment instead of an element in previous versions, is there a way for us to force react-tippy to return a valid react element instead of react fragment so we can pass things like className?

**Comment by atomiks** [comment]
I would avoid importing the core CSS yes, you can re-implement the [fade animation in a couple lines](https://github.com/atomiks/tippyjs/blob/master/src/scss/animations/fade.scss).

> We want to keep the iOS positioning stuff you mentioned

In the latest release it's not an issue, make sure the `tippy.js` version is `v6.2.3` though

> Oh sorry, one other thing I wanted to mention, because we are using styled-components we need to have a <div> or element returned instead of a React.Fragment.

I'm not sure what this means; it's returned a fragment for several versions, all it does is return the element you passed and adds a portal. I don't know why you'd need to specify an element.

**Comment by TkinterinShanghai** [comment]
I think it would be nice if you could answer this question. Theres no way of getting rid of the padding and margin as it seems. So I cant really style the tooltip however I want. I also wont be using styled components. Just css classes from tailwind. I also dont want to use themes. I just want to style the tooltips on my own

**Comment by atomiks** [comment]
> Theres no way of getting rid of the padding and margin as it seems

@TkinterinShanghai if you want to use tailwind classes then you should use Headless Tippy. You can render your own element with the classes on it. Otherwise you can just not import the CSS and style everything from scratch (or add your stylesheet after the default CSS import). Any of those will work fine.

**Comment by TkinterinShanghai** [comment]
Thanks for your really quick response. I'll check it out later
