### ISSUE TITLE
Error with Internet explorer 11  

### ISSUE THREAD

**Issue by CMalanaphyStatpro** [atomiks/tippyjs-react#212]
I am trying to use Tippy with IE11, using a basic version.
```
 <Tippy content={'Tooltip'}>
    <div>Text</div>
 </Tippy>
```
I recieve an error:
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `<<anonymous>>`, expected a single ReactElement.
in Unknown (created by ForwardRef)
in ForwardRef
in div

**Comment by jimioh** [comment]
Do you think this will be fixed? Or we will have to use a different library.

**Comment by atomiks** [comment]
I don't understand the issue, it looks like it's a `prop-types` error in DEV mode only? Or does it happen in production?

**Comment by atomiks** [comment]
Also can [try this](https://github.com/facebook/react/issues/8379), it doesn't seem to be a problem with his library.
