### ISSUE TITLE
How to provide Tippy a custom ref?

### ISSUE THREAD

**Issue by potty** [atomiks/tippyjs-react#213]
Hi, is it possible to provide Tippy a custom ref like in this example with Popper? https://material-ui.com/components/button-group/#split-button

Instead of wrapping component and using ref from children:
```jsx
<Popover visible={popoverVisible} content={popoverContent}>
  <Button onClick={togglePopover}>Toggle</Button>
</Popover>
```

Use something like this:
```jsx
<Button ref={btnRef} onClick={togglePopover}>Toggle</Button>
<Popover visible={popoverVisible} content={popoverContent} anchorEl={btnRef.current} />
```

I'm using group of Buttons as children and iterating over them, that's why I don't want to wrap my Button with Tippy.

**Comment by atomiks** [comment]
I don't think it's possible, maybe we could detect of `children` is a real DOM element already instead of a React element? So you could do, `<Tippy>{btnRef.current}</Tippy>`

**Comment by potty** [comment]
We found some workaround using different placement and hiding arrow, so Tippy now looks like it's anchored to the correct element. But I think something like `<Tippy>{btnRef.current}</Tippy>` would be pretty useful.

**Comment by reywright** [comment]
This or anything like it would be great. I started with a custom popper implementation, and I was able to replace 90% with tippy headless, except support for a custom ref to the reference element.

**Comment by atomiks** [comment]
As a workaround I think you can do this:

```jsx
// This converts the object to a function that Tippy uses
function toClientRectFunction(element) {
  if (element) {
    const fn = () => element.getBoundingClientRect();
    fn.contextElement = element;
    return fn;
  }

  return null;
}

function App() {
  const [referenceElement, setReferenceElement] = useState(null);
  const getReferenceClientRect = toClientRectFunction(referenceElement);

  return <>
    <button ref={setReferenceElement}>Reference</button>
    <Tippy getReferenceClientRect={getReferenceClientRect} />
  </>;
}
```
