### ISSUE TITLE
How to separate trigger and positioning targets?

### ISSUE THREAD

**Issue by zhaoyao91** [atomiks/tippyjs-react#215]
The raw tippy has a prop [triggerTargets](https://atomiks.github.io/tippyjs/v6/all-props/#triggertarget) which could help separate trigger and positioning targets.

How to leverage this feature in tippy-react?

**Comment by KubaJastrz** [comment]
I think you can just use it as a prop, where `children` is your positioning target and `triggerTarget` is for triggering. I remember I got this working in v3, but don't have access to the code anymore.

**Comment by zhaoyao91** [comment]
@KubaJastrz thanks, but in my situation, the positioning target could be an eternal element, meaning that I can't wrap it in the popover.

If there is an api like `target` which receives selector or element instance, that could be fine.

**Comment by KubaJastrz** [comment]
I don't think there is, but you can provide the dom element yourself. Query it in the useLayoutEffect, assign it to useState and pass it down to triggerElement. I think that would work.

You can also use core tippy if react wrapper is not sufficient.
