### ISSUE TITLE
Why does interactive in a singleton change the way tippy is inserted in the dom?

### ISSUE THREAD

**Issue by boy51** [atomiks/tippyjs-react#216]
Hi,
I am using tippy-react to show poppers inside an <svg> Element. Something like this
```
<svg>
      <Tippy singleton={source} delay={[500]} interactive />
      <Tippy singleton={target} content="Yes">
        <rect {...} />
      </Tippy>
      <Tippy singleton={target} content="Yes">
        <rect {...} />
      </Tippy>
 </svg>
```
This is working fine until I set interactive on the singleton source. Then the tippy doesn't appear anymore in my app.
So after some testing I realized that when interactive is false, the tippy is appended to the document body. Setting interactive to true changes that behaviour and tippy is behind the same dom node instead. This happens even when I move the source tippy outside the SVG.
So the solution is to set appendTo=document.body . But I'm not sure if this is good practise. The docs mention focus management for Keyboard navigation? But in the context of my app, there isn't going to be any keyboard navigation to open this popper.
So my question is, is it good practise to set appendTo, and what to look out for to preserve UX

Thanks

**Comment by KubaJastrz** [comment]
When the popper is attached next to the reference element, it will be the next thing that is focused when you press tab key. If you are saying that the content doesn't need to be focusable (eg. it's just a simple string), then feel free to attach the popper anywhere you want.

The note about keyboard management means that if you really need to attach the popper somewhere "far away" in the DOM, like document.body and keep interactive=true, then you need to use custom logic on tab key press where you focus in and out of the popper manually.

It generally should be avoided, but we all know how weird the design requirements can be sometimes :P

**Comment by boy51** [comment]
I just noticed it's mentioned in https://atomiks.github.io/tippyjs/v5/all-props/

Maybe it would be good
