### ISSUE TITLE
How to prevent "hover tunnel"-Effect with interactive singletons?

### ISSUE THREAD

**Issue by boy51** [atomiks/tippyjs-react#217]
Hi,
going through the docs I am having trouble solving this.
Lets say I have rectangle X, hovering it opens an interactive popup. In between rectangle X and the popup there happens to be a rectangle Y. Now if the user moves the mouse to the popup, he also hovers rectangle Y, and rectangle X is closed, while rectangle Y appears.
I assumed `interactiveBorder` would be the solution but it seems the interactive border doesn't apply for other Tippy triggers.
So what's the way to go here? Anyone have a solution?

**Comment by atomiks** [comment]
You could create an invisible layer element over the top that blocks pointer events, or set `pointer-events: none` on targets when the popup is open
