### ISSUE TITLE
Issues with tippyjs-react and gatsby

### ISSUE THREAD

**Issue by timidak** [atomiks/tippyjs-react#218]
Hello,
I get a weird error when I try to use tippy in my gatsby app. 😕 
Do you have any idea what is causing the error?

Here is what I tried:
```javascript
import React from 'react';
import Tippy from '@tippyjs/react';

const Technology = ({ title, fixed, description }) => (
  <Tippy content='Hello'>
    <Logo
      fixed={fixed} alt={title} title={description}
    />
  </Tippy>);
```

_And the error:_
```shell
SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '[object Object]' is not a valid selector.
```

<img width="1012" alt="Bildschirmfoto 2020-06-05 um 20 18 18" src="https://user-images.githubusercontent.com/18395108/83909960-075b0900-a76a-11ea-927c-858cd4d1c5b7.png">

Thanks in advance! 😄

**Comment by atomiks** [comment]
Hard to debug without a repro, never seen that before. Ensure the `<Logo />` component forwards its ref prop to a real inner DOM element.

**Comment by timidak** [comment]
That actually helped me very much! I used gatsby-img instead of a real `<img>` DOM element. I switched to a `<img>` and it's know working! Thank you very much! 💯

**Comment by phanirithvij** [comment]
Faced the same issue when using another library `react-inlinesvg`

```jsx
<Tippy content={`${!mapVis ? "Show" : "Hide"} Map`}>
  <SVG
    onClick={() => setmapVis(!mapVis)}
    title={"Available"}
    src={mapVis ? svgclose : svgopen}
  ></SVG>
</Tippy>
```

Was able to resolve by wrapping the <SVG /> in any native HTML tag

```jsx
<Tippy content={`${!mapVis ? "Show" : "Hide"} Map`}>
  <i>
    <SVG
      onClick={() => setmapVis(!mapVis)}
      title={"Available"}
      src={mapVis ? svgclose : svgopen}
    ></SVG>
  </i>
</Tippy>
```
