### ISSUE TITLE
Recreating SVG example in Tippy.js Demo

### ISSUE THREAD

**Issue by JeffThorslund** [atomiks/tippyjs-react#219]
I want my tooltip to appear at the cursor location when clicking on an SVG element, exactly like the SVG example in Tippy.JS Demo.

I am easily able to recreate it in vanilla JS:

https://codesandbox.io/s/bold-fire-2hfy3?file=/index.html

I cannot figure out how to achieve the same results using React:

https://codesandbox.io/s/damp-moon-4zchs?file=/src/App.js

Sorry for the beginner question, I appreciate a point in the right direction.

**Comment by atomiks** [comment]
You need to import the `followCursor` plugin and use it: https://codesandbox.io/s/musing-franklin-9vyex

The warning in the console also explains further.
