### ISSUE TITLE
unmount warning when Tippy is used as a dropdown

### ISSUE THREAD

**Issue by zslabs** [atomiks/tippyjs-react#220]
👋 Hi all! I'm looking into using Tippy for dropdowns and ran into an issue where I'm getting the following warning:

```
unmount() was called on a destroyed instance. This is a no-op but indicates a potential memory leak.
```

**Reproduction:** https://codesandbox.io/s/mystifying-engelbart-19t09

**Instructions**

1. Click on "Toggle dropdown"
2. While open, click on the "Page 2" link
3. Check console for warning

Is this warning warranted or something that I can ignore since the component is unmounted between pages? 

The warning itself makes sense, but I want to make sure there's no "garbage-collection" needed to pollute even listeners or conditionals I should be using. Thanks!

**Comment by KubaJastrz** [comment]
The [`destroy` method](https://github.com/atomiks/tippyjs/blob/bf975605aa694e1cb1ad82e964b926830243ac80/src/createTippy.ts#L1107-L1127) ([which is called when <Tippy> unmounts](https://github.com/atomiks/tippyjs-react/blob/58dfc5adcb1aa4f984036bbbc4921b45b15d7fdd/src/Tippy.js#L124)) seems to be removing unwanted listeners. I think you should be fine leaving it as is, but this is not a very educated guess :P

There probably is a reason why the instance is not completely removed from the existence, but rather assigns `instance.state.isDestroyed = true`. In any case, I'd suggest to add a check before `instance.unmount()`.

**Comment by zslabs** [comment]
Appreciate the explanation @KubaJastrz!
