### ISSUE TITLE
useSingleton() hook source can not be passed to nested Tippy elements

### ISSUE THREAD

**Issue by brendanmc6** [atomiks/tippyjs-react#227]
I am working on a tippy popper which contains nested Singleton poppers, like this:

![Kapture 2020-06-16 at 16 30 22](https://user-images.githubusercontent.com/9867865/84838237-b6aba180-afee-11ea-9578-0db5ff4712a8.gif)

Working example:
https://codesandbox.io/s/working-singleton-poppers-in-popper-ox9c1

This is only possible if you extract the outer tippy's `content` to a separate component, and call the hook inside of it.

If you use the hook at the parent level and pass the `source` object down to the elements in `content` (whether inline or via props) there is a console error: ```error: @tippyjs/react: The `source` variable from `useSingleton()` has not been passed to a <Tippy /> component.```

Broken example:
https://codesandbox.io/s/broken-singleton-poppers-in-popper-fltij?file=/src/App.js

Not being able to pass the source via props makes it harder to make composeable popper elements, like this:
```jsx
// my end goal
const ToolPalette = () => {
  const [source, target] = useSingleton();
  return (
    <ReuseablePalette target={<button>choose a tool, hover to learn more</button>} singleton={source}>
      <PaletteButton label="Paint Brush" popperContent="paintbrush.gif" singleton={target} />
      <PaletteButton label="Line Tool" popperContent="linetool.gif" singleton={target} />
      <PaletteButton label="Eraser" popperContent="eraser.gif" singleton={target} />
    </ReuseablePalette>
  );
};
```

**Comment by atomiks** [comment]
Do you think it's because the portal isn't rendered until after mount (after the effects are fired)?

https://github.com/atomiks/tippyjs-react/blob/58dfc5adcb1aa4f984036bbbc4921b45b15d7fdd/src/Tippy.js#L216-L222

I don't think that check is necessary anymore actually 🤔

**Comment by brendanmc6** [comment]
That seems plausible, I did notice the effects were firing before the child singleton had mounted.
