### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by tyteen4a03** [atomiks/tippyjs-react#230]
I'm getting these errors in my PHPStorm when trying to use Tippy in a TypeScript setting:

![Screenshot 2020-06-20 at 18 36 20](https://user-images.githubusercontent.com/440015/85206826-0064f680-b325-11ea-99b0-819017b23804.png)

**Comment by KubaJastrz** [comment]
It's an issue with IntelliJ software. https://github.com/atomiks/tippyjs-react/issues/191#issuecomment-618723275
