### ISSUE TITLE
Memory leak in v4.0.5

### ISSUE THREAD

**Issue by cecchi** [atomiks/tippyjs-react#236]
I suspect there's a memory leak when using this library, especially when used in an SSR/Node environment. The fix for https://github.com/atomiks/tippyjs-react/issues/232 was to add some state after the Tippy has mounted:

https://github.com/atomiks/tippyjs-react/compare/v4.0.4...v4.0.5#diff-a0cb345ea29dc4e75ff8f0803c94f035R120

It is unsafe to set state like this directly during the "render" phase (a.k.a. the top level scope of the function component). This state should instead be set inside a `useEffect` hook:

```tsx
useEffect(() => {
  setIsMounted(true)
}, [])
```

From our monitoring, we noticed a memory leak after bumping from `4.0.0-alpha.3` to `4.0.5` (each spike/reset is our server crashing from running out of memory. We deployed `4.0.5` late on the 29th):

![Screen Shot 2020-07-01 at 5 01 19 PM](https://user-images.githubusercontent.com/1663781/86302075-7d615d00-bbbc-11ea-8c8c-16a6d7495f8c.png)

I'm happy to open a PR, but am unfamiliar with the internals of this lib so want to make sure I'm not missing any important context.

**Comment by atomiks** [comment]
It seems both calls are already in effects

https://github.com/atomiks/tippyjs-react/blob/19991b21a9ebf942fbb863187cbb7db703f62fab/src/Tippy.js#L120

https://github.com/atomiks/tippyjs-react/blob/19991b21a9ebf942fbb863187cbb7db703f62fab/src/useSingleton.js#L16

**Comment by cecchi** [comment]
@atomiks good call -- I misread from the diff. 

False alarm! Will keep digging and reopen if we determine the memory leak is from Tippy. Thanks for the quick response!
