### ISSUE TITLE
how to show tippy at any position

### ISSUE THREAD

**Issue by phanirithvij** [atomiks/tippyjs-react#238]
Hi, I have this circular progress ring thing I've implemented in react.
Using svg circles and `stroke-dashoffset`.

So my task is I need to show the tooltip something like 
![nodes-progress](https://user-images.githubusercontent.com/29627898/86515237-34680d80-be35-11ea-9100-1c569699a987.png)

But I'm having the svgs on top of each other so not sure how to use `<Tippy></Tippy>` for each sector segment of the circumference. **[CODE](https://user-images.githubusercontent.com/29627898/86515411-51e9a700-be36-11ea-92ab-e679ae6ce5e4.png)**

So I can only see the topmost tooltip as of now.

Ignore the black dots.
![image](https://user-images.githubusercontent.com/29627898/86515221-17333f00-be35-11ea-9de6-6af379860713.png)

## I was thinking of displaying a tippy at any given mouse position but couldn't find it in the docs.

I'm fine with using the regular `tippy.js` instead of the react one but as my codebase is React, asking the question here.

**Comment by phanirithvij** [comment]
I've figured it out.
```js
        // I'm Handling multiple tooltips so I have an array
	let [tooltips, setTooltips] = useState(tippy("#tooltip-controller"));

	const showTippy = () => {
		if (tooltips.length > 0) {
			if (!tooltips[0].state.isVisible) tooltips[0].show();
		}
	};

	const hideTippy = () => {
		if (tooltips.length > 0) {
			if (tooltips[0].state.isVisible) tooltips[0].hide();
		}
	};

	useEffect(() => {
		tippy("#tooltip-controller", {
			followCursor: true,
			plugins: [followCursor],
			content: "",
			onCreate: (tool) => {
				setTooltips([tool]);
			},
		});
	}, []);
...
	<div
		onMouseMove={(ev) => handleTippy(ev)}
	>
....

```

In `handleTippy`

```js
       // if in desired region
// for my eg. I'm calculating distance from the circle center and the stroke width compensation to get the circumference rings region
	if (
		distsquared < radius ** 2 &&
		distsquared > (normalizedRadius - stroke) ** 2
	) {
		showTippy();
	} else {
		hideTippy();
	}

...

	const showTippy = () => {
		if (tooltips.length > 0) {
			if (!tooltips[0].state.isVisible) tooltips[0].show();
		}
	};

	const hideTippy = () => {
		if (tooltips.length > 0) {
			if (tooltips[0].state.isVisible) tooltips[0].hide();
		}
	};

```

**Comment by phanirithvij** [comment]
How dumb was I just a few mins ago?

https://github.com/atomiks/tippyjs-react#visible-boolean-controlled-mode is enough with `followCursor` enabled

And boundary checking

```js
       // if in desired region
      // for my eg. I'm calculating distance from the circle center and the stroke width compensation to get the circumference rings region
	if (
		distsquared < radius ** 2 &&
		distsquared > (normalizedRadius - stroke) ** 2
	) {
		show();
	} else {
		hide();
	}

...

```

**Comment by atomiks** [comment]
To be fair that wasn't really properly supported until like 2 days ago I think (`followCursor` + `show`/`hide` methods) 😆
