### ISSUE TITLE
Headless popover with interactive content is not hidden on blur

### ISSUE THREAD

**Issue by danielr18** [atomiks/tippyjs-react#239]
Sandbox: https://codesandbox.io/s/vigilant-kowalevski-yw87k?file=/src/App.js

I think the issue is in this function:
https://github.com/atomiks/tippyjs/blob/7b9354ea9edd30943475bbee1c5d2f88d8b19d76/src/createTippy.ts#L549

```
function onBlurOrFocusOut(event: FocusEvent): void {
    if (
      instance.props.trigger.indexOf('focusin') < 0 &&
      event.target !== getCurrentTarget()
    ) {
      return;
    }

    // If focus was moved to within the popper
    if (
      instance.props.interactive &&
      event.relatedTarget &&
      popper.contains(event.relatedTarget as Element)
    ) {
      return;
    }

    scheduleHide(event);
  }
```

The conditional below `// If focus was moved to within the popper` handles the case when you focus from the trigger to an element inside the popover, but then when you focus to another trigger from an element inside the popover, nothing hides it.

**Comment by atomiks** [comment]
See https://github.com/atomiks/tippyjs/issues/744#issuecomment-603631934
