### ISSUE TITLE
Export tippy types from @tippyjs/react?

### ISSUE THREAD

**Issue by katarc** [atomiks/tippyjs-react#240]
Can tippy types be exported out from @tippyjs/react (such as Instance, Plugin, etc) -- I would want to avoid downloading tippy.js library just for the types

**Comment by KubaJastrz** [comment]
`tippy.js` is a dependency of `@tippyjs/react` so you are downloading it anyway. I guess we should treat the types the same as we do in case of css files - so leave in the core library without any re-exporting and let people import from `tippy.js`.

That's what I've been doing in my projects and I didn't find it troublesome 🤷
