### ISSUE TITLE
How to detect when popper "flips" with headless implementation

### ISSUE THREAD

**Issue by stevebertan** [atomiks/tippyjs-react#243]
I'm following the example of using Tippy.js with React Spring: https://codesandbox.io/s/vigilant-northcutt-7w3yr

Is there a way to detect when popper flips or changes target location `onMount`?  I'm trying to create a directional animation but I'm not able to determine when the placement is automatically changed in order to update the React Spring animation to reflect the new placement.

**Comment by atomiks** [comment]
I think you might need to create a custom popper modifier and read its `placement` state.

**Comment by stevebertan** [comment]
That worked, thank you for pointing me in the right direction!
