### ISSUE TITLE
styling using styled component issue

### ISSUE THREAD

**Issue by net-bet** [atomiks/tippyjs-react#245]
Hi, I want to change the arrow and wrapper of the tooltip background.
For some reason, this example didn't work to me:

const PurpleTippy = styled(Tippy)`
  background: purple;

  /* Styling the arrow for different placements */
  &[data-placement^='top'] > .tippy-arrow::before {
    border-top-color: purple;
  }
`;

The background (of the content only) changed to purple, but the arrow and the content wrapper/box stayed transparent.

How can it be?

This is the code:

    <div style={{ display: 'flex' }}>
      <PurpleTippy
        content={<span>Tooltip</span>}
      >
        <div>asdasd</div>
      </PurpleTippy>
    </div>

I also tried to explicitly set placement and arrow value as props.

**Comment by atomiks** [comment]
Are you importing the CSS?

**Comment by net-bet** [comment]
I see, when I am importing the CSS it works.
Isn't it possible at all without importing a CSS?
I don't want to load CSS file in application.

In general, all I want is to paint the arrow placement, anything else I can do 

If that is possible, it would be pure awesomeness.
I believe I am not the only one which that helps him.

https://codesandbox.io/s/reactjs-popup-issue-template-forked-qpmuc?file=/src/index.js

Much thanks :)

**Comment by atomiks** [comment]
Well the CSS is what provides the base arrow styling to use. If you don't want to import the CSS you have to style the arrow yourself

**Comment by net-bet** [comment]
Is there a way I can add this css with a css-in-js style? someway or another to inline it.

I tried to copy the css under the "styled", but it doesn't work.
I assume because of the positioning of the tooltip or something like that.

I understand it is not trivial, I do think it might be very valuable not just for me.
