### ISSUE TITLE
Tippy doesn't close when loses focus

### ISSUE THREAD

**Issue by Joozty** [atomiks/tippyjs-react#246]
When I try to navigate only with the keyboard (using Tab) and my tooltip is interactive and it loses focus it doesn't get closed.

Code example:
```jsx
import React from "react";
import Tippy from "@tippyjs/react/headless";

const HeadlessTippy = () => (
    <Tippy
      interactive
      render={(attrs) => (
        <div {...attrs}>
          <input type="text" />
        </div>
      )}
    >
      <button>My button</button>
    </Tippy>
);

export default HeadlessTippy;

```

See demo [here](https://codesandbox.io/s/tippy-react-focus-lpvd6?file=/src/App.js) - just focus the window and press tab several times.

Thanks

**Comment by atomiks** [comment]
See https://github.com/atomiks/tippyjs/issues/744#issuecomment-603631934
