### ISSUE TITLE
Singleton tippys fail to show in child components

### ISSUE THREAD

**Issue by thoughtsofcode** [atomiks/tippyjs-react#253]
## Bug description

Tippys that are part of a singleton don't work after child components are mounted/unmounted. Non-singleton tippys don't exhibit this problem. See the linked CodePen example below.

## Reproduction

CodePen link: https://codepen.io/thoughtsofcode/pen/wvGyKRQ

The _Tab 1_ tippy initially works. If you switch tabs, _Tab 1_ is unmounted and _Tab 2_ is mounted. If you hover over _Tab 2_, the corresponding tippy doesn't show. Now if you switch back to _Tab 1_, the tippy no longer works.

**Comment by FlorianWendelborn** [comment]
Same issue here. @thoughtsofcode, did you figure out a workaround for this?

**Comment by benjaminsuch** [comment]
Change:
```jsx
{ selectedTab === "tab1" ?  <Tab1 target={props.target} /> : <Tab2 target={props.target} /> }
```

To:
```jsx
{ selectedTab === "tab1" ?  <Tab1 ref={props.target} /> : <Tab2 ref={props.target} /> }
```

I think this is not ideal since you (probably) don't want `ref` to be used for a Tooltip. Taking a closer look in the source code, I think `forwardRef` in `src/forwardRef.js` might help you. If I'm not wrong you have to preserve the ref to `target`, which get's lost on a re-render.
