### ISSUE TITLE
`onShown` not firing

### ISSUE THREAD

**Issue by liubko** [atomiks/tippyjs-react#254]
version 4.1.0
related issue https://github.com/atomiks/tippyjs-react/issues/162 

## Description

`onShown` callback never get fired. Here is an example demo https://codesandbox.io/s/jumping-tooltip-forked-o5px3?file=/src/index.js

**Comment by atomiks** [comment]
`onShown` relies on CSS transitions, so you'd need to import the CSS or implement your own.

> Since this is achieved via CSS transitionend, it relies on your own event listeners if using a custom render function. You'll need to call the lifecycle manually in this case.
