### ISSUE TITLE
Singleton interactivity hides element intermittently 

### ISSUE THREAD

**Issue by zslabs** [atomiks/tippyjs-react#256]
👋 

Repo: [Code Sandbox](https://codesandbox.io/s/objective-cray-oslwz)

The above sandbox is fairly similar to the Singleton demo from the docs, with an `interactive` prop added to the `source` Tippy. If you hover over each `target` Tippy and then move into the interactable area and back, sometimes the content will persist and others it will hide, especially when you perform a diagonal move to another reference element. I've tried `interactiveBorder` but that was not working as intended. If I remove the singleton, the hover/open state persists as it should. 

Thanks as always!

cc @atomiks

**Comment by zslabs** [comment]
Is the `interactive` prop not compatible with the Singleton due to https://github.com/atomiks/tippyjs/blob/ea753de47a27418f317296020fe9807f3ad1b117/src/createTippy.ts#L773 ?

**Comment by atomiks** [comment]
Sorry for the late response but this should be fixed in the latest versions of both libs. Upgrading to `tippy.js@6.2.6` and `tippyjs/react@4.1.0` in the Sandbox shows that.
