### ISSUE TITLE
Tippy auto dropup for custom component

### ISSUE THREAD

**Issue by mertohancan** [atomiks/tippyjs-react#258]
Is it possible to get tippy's automatic dropup property by wrapping my custom dropdown component? I just want to use tippy's automatic, up or down opening property according to position of element..

```
  {toggleDropdown && (
     <Tippy>
          <CustomDropdown />
        </Tippy>
      )}
```

**Comment by atomiks** [comment]
> automatic dropup property

I'm not sure what this is exactly?

**Comment by mertohancan** [comment]
> > automatic dropup property
> 
> I'm not sure what this is exactly?


tippy automatically opens the element from above if there is no space at the bottom of the screen.

**Comment by mertohancan** [comment]
Actually, it is possible with `{...attrs}` props but it breaking the style

**Comment by atomiks** [comment]
You need to set `interactive` prop to true and maybe some other styling changes

**Comment by mertohancan** [comment]
It works but I have to put {children} in <Tippy>  with interactive props . Otherwise, I got `Cannot read property 'contains' of null` error. When I put <div />`(<Tippy ...otherProps><div/><Tippy/>) `my dropdown does not set auto placement according to the screen. If there is no place below, it opens from below.
