### ISSUE TITLE
Show delay value is not applied in Chrome Dev Tools touch/responsive mode

### ISSUE THREAD

**Issue by brendanmc6** [atomiks/tippyjs-react#262]
This may be chrome specific and not a tippy issue, but I thought I should bring it to your attention.

1. open the codesandbox below
2. open devtools
3. switch devtools to responsive mode (with touch simulator)
4. tab onto the button and observe that no 500ms delay is applied.

# Repro and summary
https://codesandbox.io/s/tippy-delay-error-lu56e

**Comment by atomiks** [comment]
Can you try it with the new package/version? `@tippyjs/react`

**Comment by brendanmc6** [comment]
Hmm I can reproduce this in my project with 4.2.0, but no longer able to reproduce in codesandbox.
Will reopen once I get it working in codesandbox.
