### ISSUE TITLE
Tippys that are nested inside interactive tippys teleport on re-renders

### ISSUE THREAD

**Issue by itayganor** [atomiks/tippyjs-react#264]
Reproduction steps
===

1. Go to https://codesandbox.io/s/tippyjs-interactive-teleport-4cpy8
2. Hover on the *Hover me* label, then hover on the *Hover me too* label.
3. Notice that when the state changes (not even a state related to the tooltips), the nested tippy teleports to the top left (but not exactly).

I'll note that in my app, the nested tippy teleports to a top-lefty point of the screen, but not to that corner exactly. I think the wrong calculation positions the nested content with `position: absolute; top: 0; left: 0;`, and shows the nested tooltip there.

You can see that if we copy the content's dimensions into that point, the nested tooltip is perfectly positioned according to it:

![image](https://user-images.githubusercontent.com/6430313/96347585-45b6ec00-10ab-11eb-8040-f4e1d109bd30.png)

**Comment by atomiks** [comment]
Interestingly it seems like the [code](https://github.com/atomiks/tippyjs/blob/beaff3e46caa5e40ef23ec3b40ebc1ab567feaac/src/createTippy.ts#L892-L900) introduced to fix [this](https://github.com/atomiks/tippyjs-react/issues/177) broke this particular case.

**Comment by itayganor** [comment]
Thanks for the quick fix, it served me well. Unfortunately, one of the parent elements has `position: relative`, which makes the tippy element be super narrow :\ Is there anything new in Tippy/Popper that may solve this issue?

**Comment by DominikGuzei** [comment]
Unfortunately, we also have this issue, and appending to the parent element is not a good option 😢

**Comment by atomiks** [comment]
@DominikGuzei i'm gonna take a look again today, IIRC the problem was hard to solve because while I did find something that mostly-worked when I checked in October, it had 1 small issue with a 1 frame glitch in terms of positioning

**Comment by atomiks** [comment]
So there's a 1 frame glitch if the nested tippy is flipping but it fixes the core issue. 

I think that issue has to do with the scroll events and when they fire (the nested one must be firing first, but needs to fire once the parent has been repositioned. I think you can fix this with a modifier.)

**Comment by DominikGuzei** [comment]
Thanks for the super-fast response @atomiks, I'm testing version `4.2.1` now to see if this is fixed in our case :) do you take donations for your open source work?
