### ISSUE TITLE
getReferenceClientRect doesn't work as expected

### ISSUE THREAD

**Issue by sharno** [atomiks/tippyjs-react#265]
I found out about the `getReferenceClientRect` prop, when trying to use it according to the types of TS, it looks like I should pass a function that returns a `DOMRect` but that doesn't work as expected and after digging deeper I found out that I need to pass in this prop a function with this signature `() => () => DOMRect` which seems to work for me

Is that expected?

**Comment by atomiks** [comment]
Can you post a full repro?

**Comment by sharno** [comment]
My apologies, when I tried to do a minimal example, it worked as expected. So probably it's a problem with my setup in the actual project.
