### ISSUE TITLE
disable flip behavior of tooltip

### ISSUE THREAD

**Issue by sagarCS** [atomiks/tippyjs-react#268]
hey folks,
I have list of item and each item has tooltip that open at top when we hover over it,
my problem is my list start from top of the dom and when i hover on 1st three items the tooltip get opens but at the bottom not on the top so i want to disable that automation flip behavior of tooltip, can i do it or any hacks i can do to achieve this?

**Comment by atomiks** [comment]
If it opens at the bottom it means it can't fit on top, so it'll be cut off. Yes you can use the flip popper modifier to disable flipping.

**Comment by sagarCS** [comment]
can you give me some code example on how to use poper modifier in code sandbox or here itself, because i have been using your default tippy component. i want to disable flipping behavior. 
Thanks for the reply.

**Comment by atomiks** [comment]
`<Tippy popperOptions={{ modifiers: [{ name: 'flip', enabled: false }] }} />`

**Comment by sagarCS** [comment]
Thanks @atomiks  i will try this out and see if it solves my problem, cheers!

**Comment by sagarCS** [comment]
hey @atomiks , one more help....If you see the screenshot below you can see that tooltip is half hidden behind the left section of the Dom thats because the parent element has property overflow: true which cause tooltip to get behind the dom even if its z-index is set to max for tooltip, is there a way i can make that tooltip to appear on top.
![Screenshot from 2020-11-01 12-40-12](https://user-images.githubusercontent.com/61415134/97797051-9a2ba100-1c3f-11eb-9dcb-2c4c9c30b373.png)

**Comment by essmahr** [comment]
@sagarCS You will have to use the `appendTo` prop to attach the popper element to something else (something outside the scroll container).

There is no way for an element sitting inside a container with `overflow: auto` to appear outside that container (I'm assuming you're using the `interactive` prop which will render the popper next to its target element)

The other option here is to ensure your popper element never gets wider than the container (is there perhaps some CSS making it wide?)

**Comment by sagarCS** [comment]
@essmahr  thanks for the suggestion of apptoTo prop i will look itno this as i have no idea how to use appenTo props.
and the popper element is wider beacuse there is some data on right side as well which is hidden due to overflow property.
do you have a example or some codesandbox sample for appenTo props?
