### ISSUE TITLE
Add a `enabled` prop to the Tippy component

### ISSUE THREAD

**Issue by rmbagel** [atomiks/tippyjs-react#269]
First off, great library. Thank you for your hard work.

I noticed a code-smell when using a tooltip on a disabled button. Right now, my Tippy wrapper needs to be passed the opposite value of the disabled prop that is passed to the button-- which is confusing to read.

```
        <Tippy content={"This is disabled"} disabled={!buttonDisabled} placement="bottom">
          <span>
              <button className="btn btn-default" disabled={buttonDisabled}>
                End
              </button>
          </span>
        </Tippy>
```

If there was an `enabled` prop, I think the code would be more clear:

```
        <Tippy content={"This is disabled"} enabled={buttonDisabled} placement="bottom">
          <span>
              <button className="btn btn-default" disabled={buttonDisabled}>
                End
              </button>
          </span>
        </Tippy>
```

What do you think? My assumption is that an `enabled` prop could just be inverted into a `disabled` value, but I haven't looked deeper into the Tippy codebase.

**Comment by atomiks** [comment]
`disabled` was chosen as it is consistent with HTMl element attributes.
