### ISSUE TITLE
usage with virtual element

### ISSUE THREAD

**Issue by lukesmurray** [atomiks/tippyjs-react#271]
Is it possible to use this library with [virtual elements](https://popper.js.org/docs/v2/virtual-elements/) from popper js?

**Comment by atomiks** [comment]
`getReferenceClientRect` is for virtual elements. If you need to set `contextElement` you can set it on the function.

````js
const getReferenceClientRect = () => ({...});
getReferenceClientRect.contextElement = someNode;
```

**Comment by lukesmurray** [comment]
thanks that resolves the issue!

**Comment by baba43** [comment]
How does this work in practice  @lukesmurray? What prop can be used to attach a virtual element to a Tippy component?
