### ISSUE TITLE
Multiple instances appear when hovering and focusing at the same time

### ISSUE THREAD

**Issue by kripod** [atomiks/tippyjs-react#272]
When a button with a tooltip has keyboard focus, it shows a Tippy instance as intended. However, when hovering over the same button when it's already focused, another Tippy instance gets created, duplicating the shadow effect of the button's intended tooltip.

Intended look (with focus only):

<img width="110" alt="image" src="https://user-images.githubusercontent.com/14854048/99654567-cd04d000-2a5a-11eb-9033-419e70b9dedf.png">

Buggy look with too much shadow (with both hover and focus):

<img width="110" alt="image" src="https://user-images.githubusercontent.com/14854048/99654636-e4dc5400-2a5a-11eb-8b03-aa8fe2acc1a7.png">

Cause of the buggy look (newly appearing Tippy element as I hover my mouse over the focused button):

![image](https://user-images.githubusercontent.com/14854048/99656115-ce36fc80-2a5c-11eb-8702-faf81d3705ca.png)

**Comment by atomiks** [comment]
This is likely something wrong with your implementation. Try creating a Codesandbox to reproduce it.

**Comment by kripod** [comment]
Thank you for replying! Indeed, it seems to have happened in a complex relative+absolute positioning context which I cannot reproduce. Wrapping the button with the tooltip on it inside a `div` and then applying `position: absolute` on the outer `div` rather than the button itself seems to solve the issue. It's a bit weird, though.
