### ISSUE TITLE
Jumping of page when moving the mouse over items in a tippy instance

### ISSUE THREAD

**Issue by abraxxas** [atomiks/tippyjs-react#273]
Hi,

We are experiencing issues on our page where we have a list of items that are displayed and each item has an interactive tippy dropdown. When opening one of these dropdowns and moving the mouse over the items in the dropdown the whole page starts to jump. We would like to know if you have any suggestions on how we could debug this properly if it is related to tippy or popper. 

We do not use the followCursor plugin and we have already tried playing around with the popper options to disable flipping and to set a fixed placement for the dropdown. But nothing seems to have an effect. See the following gif for the behaviour. 
![jumpy](https://user-images.githubusercontent.com/8842038/99792944-30a8ff00-2b28-11eb-858e-50241ee2244d.gif)

**Comment by fabb** [comment]
nvm, was not caused by tippy but rather by our own client code. browsers behave weirdly when calling `focus()` on the menu
