### ISSUE TITLE
Put Tippy component on the Tippy global

### ISSUE THREAD

**Issue by hornta** [atomiks/tippyjs-react#277]
We are using the UMD build of this library and we expect the Tippy component to be put on window.Tippy but right now it's placed on Window.Tippy.default. Can this be changed in the build?

Right now I have to rename the default to something other than Tippy.

```jsx
const { default: TippyReact } = Tippy;

<TippyReact>
```

But I want to use it like this:

```jsx
<Tippy>
```

**Comment by atomiks** [comment]
Couldn't you do this:

```js
window.TippyReact = TippyReact.default;

<TippyReact>
```
