### ISSUE TITLE
Controlled mode delay prop doesn't do anything

### ISSUE THREAD

**Issue by lukesmurray** [atomiks/tippyjs-react#278]
In controlled mode the [delay prop](https://atomiks.github.io/tippyjs/v6/all-props/#delay) does not delay the visibility of the tippy. Wondering if this is purposeful? I can put together a codesandbox if necessary.

Update: [here is a code sandbox](https://codesandbox.io/s/create-react-app-typescript-forked-t5ifb?file=/src/index.tsx) reproducing the issue

**Comment by atomiks** [comment]
Indeed it is, because with controlled mode, you need to create the timeouts yourself. `show` / `hide` are instantaneous

**Comment by lukesmurray** [comment]
thank you that makes sense!  I was able to put together a delay function like you said.
