### ISSUE TITLE
How to make tippys work with animated content dimensions?

### ISSUE THREAD

**Issue by itayganor** [atomiks/tippyjs-react#280]
I have a tooltip in my application whose content is dynamic and has `transition`.

It seems like tippy can't keep up with the animation frames, and only takes the first animation frame into consideration and calculation.

I made a quick reproduction of the issue using the great `react-animate-height`'s AnimateHeight component:

![9bccfd19-f5c0-4746-9083-7044c93123c3](https://user-images.githubusercontent.com/6430313/103384192-2baf7600-4afe-11eb-8aea-e3cf488789cc.gif)

[CodeSandbox](https://codesandbox.io/s/tippyjs-content-animation-gx86t)

How can I make the tippy (probably even the popper) know I'm animating the content, and it has to recalculate its position in every frame?

Thanks! <3

**Comment by atomiks** [comment]
You can use the `sticky` plugin:

https://codesandbox.io/s/tippyjs-content-animation-forked-scu65?file=/src/App.js

Looks like Chrome broke something recently though in a new version 🙄 it works perfectly in Firefox and used to work in Chrome

**Comment by itayganor** [comment]
> You can use the `sticky` plugin:
> 
> https://codesandbox.io/s/tippyjs-content-animation-forked-scu65?file=/src/App.js
> 
> Looks like Chrome broke something recently though in a new version 🙄 it works perfectly in Firefox and used to work in Chrome
> 
> Edit: nevermind, it just had to be refreshed lol

Cool, thanks.

It looks like the implementation of `sticky` is a bit heavy for performance, maybe we could benefit from `ResizeObserver` here.

Here's a quick plugin I made to reposition the popper when its content changes dimensions:

```ts
import ResizeObserver from 'resize-observer-polyfill';


const resizeObserved = {
    name: 'resizeObserved',
    defaultValue: false,
    fn(instance) {
        const {popper} = instance;
        const ro = new ResizeObserver(onResize);

        function onResize() {
            instance.popperInstance.update();
        }

        return {
            onMount(): void {
                ro.observe(popper);
            },
            onUnmount(): void {
                ro.unobserve(popper);
            },
        };
    },
};

export default resizeObserved;
```

**Comment by atomiks** [comment]
I guess the sticky plugin should use that by default now and fallback to the animation frame method.
