### ISSUE TITLE
Usage with react-textarea-autosize (rendering detached from DOM?)

### ISSUE THREAD

**Issue by maxsalven** [atomiks/tippyjs-react#284]
I ran into an issue with react-textarea-autosize and this library:
https://github.com/Andarist/react-textarea-autosize/issues/303

Any thoughts on if there is a solution to be had from the tippy side of the equation?

**Comment by atomiks** [comment]
You need to lazify the component. There's a link in the README.

**Comment by maxsalven** [comment]
Thanks James, I've tried that but it hasn't helped:

https://codesandbox.io/s/romantic-star-dp9qr?file=/src/App.js

**Comment by atomiks** [comment]
Change `onShow` to `onMount` and it works, that should probably be updated to use that hook instead
