### ISSUE TITLE
Incorrect path to CSS file

### ISSUE THREAD

**Issue by marcolilli** [atomiks/tippyjs-react#285]
The path proposed in the [README](https://github.com/atomiks/tippyjs-react/blob/master/README.md#default-tippy) to import tippy's CSS file does not work after I switched from **@tippy.js/react** to **@tippyjs/react**.

I've imported the file as stated in the README.md with `import 'tippy.js/dist/tippy.css'; `

The same code worked before switching to **@tippyjs/react**

### Complier error:
```
Failed to compile.

./src/components/presentation/ToolTip.js
Module not found: Can't resolve 'tippy.js/dist/tippy.css' in '{path to project}/src/components/presentation'
```

|                   | Version | 
| ---------- |--------:| 
| **React**  | 17.0.1    | 
| **node**   | 6.14.11  |  
| **npm**    | 14.15.1  |

**Comment by KubaJastrz** [comment]
can you make a [reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? it is still here as it was before: https://unpkg.com/browse/tippy.js/dist/tippy.css

**Comment by marcolilli** [comment]
@KubaJastrz Actually I can't. I'll try to spot the differences between the sandbox and my project. Therefore closing for now.
