### ISSUE TITLE
Update typescript definition for headless render

### ISSUE THREAD

**Issue by 9oelM** [atomiks/tippyjs-react#286]
Thank you for writing this wonderful library. Really making use of it.

Just got one little thing: As per #259, receiving `instance` as a parameter in the callback method in `render` prop has become possible, but it seems that the example in README and typedef in `index.d.ts` have not yet been updated. Could we get them updated?

**Comment by KubaJastrz** [comment]
Certainly, do you want to do a PR?

**Comment by 9oelM** [comment]
sure. will do soon

**Comment by atomiks** [comment]
Updated it
