### ISSUE TITLE
The non-minified UMD build contains "process" which crashes in the browser

### ISSUE THREAD

**Issue by hornta** [atomiks/tippyjs-react#287]
The UMD build output should strip all usages of process so that it can be used in the browser without having to mock a process variable on window.
It's currently only the minified UMD build that strips process but the non-minified build should also not have process usages.
https://github.com/atomiks/tippyjs-react/blob/master/rollup.config.js#L46

**Comment by atomiks** [comment]
The point of developing is to get helpful warnings though, you just mock it in order to get them.
