### ISSUE TITLE
Missing v4.2.3 tag?

### ISSUE THREAD

**Issue by ybiquitous** [atomiks/tippyjs-react#289]
Hi, we can get the version 4.2.3 from npmjs.com, but the tag v4.2.3 seems missing on GitHub.

- https://www.npmjs.com/package/@tippyjs/react/v/4.2.3
- https://github.com/atomiks/tippyjs-react/releases/tag/v4.2.3 => 404 😢

**Comment by atomiks** [comment]
Oh yeah, I just left a console.log in the package, that's all that version fixes lol 🙄

**Comment by ybiquitous** [comment]
Thanks. I got it. 👍
