### ISSUE TITLE
[Bug] `deepPreserveProps` results wrong modifier configuration

### ISSUE THREAD

**Issue by SunriseFox** [atomiks/tippyjs-react#290]
Hi. This is a bug report.

Here in this commit you `uniqueByName` the modifiers that I pass into...

https://github.com/atomiks/tippyjs-react/commit/7198256fe41c8bb347a3aed4f677b8b01dc7629c#diff-3274f1a37032fb0ae4e2823def0007c634e869ae0dfc304ff6a12c36513c3a52R55

And while fixing #264, this function will be called whenever an update is made.

If I have 

```js
popperOptions = {
  modifiers: [
    {name: "flip", enabled: true},
    {name: "flip", enabled: false}
  ]
}
```

`deepPreserveProps` unique them by their name so I got

```js
popperOptions = {
  modifiers: [
    {name: "flip", enabled: true},
  ]
}
```

... but actually what I want is

```js
popperOptions = {
  modifiers: [
    {name: "flip", enabled: false}
  ]
}
```

![image](https://user-images.githubusercontent.com/14029711/110446158-d4c7ad80-80f9-11eb-9f51-58268375a521.png)

Thanks.

**Comment by atomiks** [comment]
Will uniquing them in reverse order work? The reason it was added was because I think there was a potential memory issue with multiple modifiers getting added if they were the same in some update cases.

**Comment by atomiks** [comment]
That commit was meant to be a pull request but can you verify it? @SunriseFox

**Comment by SunriseFox** [comment]
> Will uniquing them in reverse order work? The reason it was added was because I think there was a potential memory issue with multiple modifiers getting added if they were the same in some update cases.

No... I don't think it will work well as popperjs has a rule to resolve the configurations of modifiers.  For example

```js
popperOptions = {
  modifiers: [
    {
       name: "flip", 
       options: {
         fallbackPlacements: ['top', 'right'],
       }
    },
    {name: "flip", enabled: true}
  ]
}
```

the result will still be wrong...

**Comment by atomiks** [comment]
Maybe we can unique by `JSON.stringify(modifier)`, that way the true duplicates will be removed...

**Comment by KubaJastrz** [comment]
Wouldn't that make more sense for the deduplication to be implemented in popper-core, instead of the Tippy which is only popper's consumer?

**Comment by atomiks** [comment]
@KubaJastrz it already is (they get merged). The problem here is just fixing a memory issue with lots of modifiers being re-added when the instance gets updated. Actually the objects might be the same reference, so we could dedupe with a map instead

**Comment by atomiks** [comment]
So we can't dedupe with a map, there's an example in the demo where the reference is always different (in the JSX), but stringify should work in almost all cases, but I've merged a fix
