### ISSUE TITLE
Is it possible to use Tippy in default mode, but with a lazy `content` prop?

### ISSUE THREAD

**Issue by marcelgerber** [atomiks/tippyjs-react#308]
Hey! At Our World in Data, we've implemented a tooltip for our charts using Tippy, and we very much like how easy this is to set up and use. Great work!

However, since our charts can have tens or even hundreds of different tooltips, it is quite wasteful to pre-render every one of them with the chance that a user happens to stumble upon it.

Would it therefore be possible to make the `content` prop lazy, i.e. of the type `React.Element | () => React.Element`? This would then mean that `content` is only evaluated when it is needed: when the tooltip is shown.

For an example of what we would like to have, let's consider the following example:
```jsx
import "./styles.css";
import Tippy from "@tippyjs/react";
import "tippy.js/dist/tippy.css";

export default function App() {
  const numbers = [...Array(1000).keys()];

  return (
    <div className="App">
      {numbers.map((num) => (
        <Tippy content={() => `Squared: ${num ** 2}`}> {/* <----- this is what we would like to have */}
          <div>Number {num}</div>
        </Tippy>
      ))}
    </div>
  );
}
```

You can also see this on [CodeSandbox](https://codesandbox.io/s/tippy-lazy-content-sz1hd?file=/src/App.js).

I've attached a screenshot of our use case below. Every different bar has its own tooltip, and the number of tooltips can then quickly grow to many more than in this screenshot.

<details>
<summary>Screenshot of our Tippy usage</summary>

![](https://user-images.githubusercontent.com/2641501/119535355-2e01bd80-bd88-11eb-8484-bd65938ab26a.png)

</details>

**Comment by KubaJastrz** [comment]
You can load the `content` in a lazy fashion yourself for the time being. Take a look at #209 for examples.

**Comment by MarcelGerber** [comment]
Hi @KubaJastrz, thank you for the quick response.

For the record, I would also like this to be a supported behaviour of Tippy out of the box. But for now, that workaround works well for us!

**Comment by gajjardarshithasmukhbhai** [comment]
Hi @KubaJastrz, we are used to tippy-react in our Micro FrontEnd app. so if we add appendTo={() => document.body} so it will display well in react but not displaying well in ember. In ember, we only copy and paste it out of react build. again want to repeat we are used to micro frontend Architecture, Thanks.
