### ISSUE TITLE
Tooltip doesn't hide when the cursor leaves the reference element

### ISSUE THREAD

**Issue by ryanjmack** [atomiks/tippyjs-react#310]
tippy tooltips don't hide in some instances when the cursor leaves the reference element

In the [tippy demo](https://atomiks.github.io/tippyjs/), if you trigger the default tooltip and then scroll, the tooltip stays fixed and doesn't hide until it reaches the edge of the page or the scroll event ends.

Is there a way to always hide the tooltip when the cursor leaves the reference element? Even better if we could enable this behavior in uncontrolled tooltips

**Comment by KubaJastrz** [comment]
You can use `instance.hide()` to hide the tooltip programmatically if you want uncontrolled behavior.

For example, you can listen to the native `scroll` event and fire the `hide()` method if needed.

**Comment by ryanjmack** [comment]
Thanks! It worked nice, we setup the listener in the `onTrigger` lifecycle method

**Comment by resthedev** [comment]
> Thanks! It worked nice, we setup the listener in the `onTrigger` lifecycle method

Hey thanks fro explaining how you did it. Did you also cleanup the listener with `removeEventListener`? How did you do this when the listener takes in a parameter (instance)?
