### ISSUE TITLE
Interactive tooltip disappears when clicking into a select on Firefox

### ISSUE THREAD

**Issue by Moki-19** [atomiks/tippyjs-react#312]
Hi,

If an interactive tooltip contains a `<select>` component, when I click inside the `<select>` to choose an option, the whole tooltip disappears on **Firefox** (works as expected on Chrome and Safari).

Here a minimal code to demonstrate the issue :
https://codesandbox.io/s/nameless-snow-wt6u7

Thank you for your help.

**Comment by Moki-19** [comment]
Thank you for your reply. Sadly, using `trigger: "click"` as a workaround should not be an option in our context.

By "core lib", do you mean `PopperJs` library ?

**Comment by atomiks** [comment]
Core lib as in `tippy.js`, which it's now fixed in latest version

**Comment by atomiks** [comment]
If you're using npm, reinstalling `@tippyjs/react` will upgrade `tippy.js` with it (last time I used npm). If you're using Yarn, you can use `resolutions` in `package.json` to specify the latest Tippy or editing the lockfile.
