### ISSUE TITLE
Disable all animation on test environment

### ISSUE THREAD

**Issue by Sabrinovsky** [atomiks/tippyjs-react#315]
While testing, i dont want tippy to have any animation, so specs runs faster.
I was looking for the tippyjs it self and found this.
Is there's any way to get to this approach here?

https://github.com/atomiks/tippyjs/issues/198

The react transition group does something similar:

https://reactcommunity.org/react-transition-group/testing

**Comment by mayank99** [comment]
You can already do `animation={false}`

**Comment by Sabrinovsky** [comment]
> You can already do `animation={false}`

I want to disable the animation for all typpies, but just when running the specs.

**Comment by mayank99** [comment]
Maybe you can use it with [`tippy.setDefaultProps`](https://atomiks.github.io/tippyjs/v6/methods/#setdefaultprops)

**Comment by atomiks** [comment]
You can create your own wrapper in your test files which sets `animation={false}` and import from that instead when testing.
