### ISSUE TITLE
Inside of a tippy singleton, incorrect attrs are passed to render prop

### ISSUE THREAD

**Issue by ryanjmack** [atomiks/tippyjs-react#317]
Hello,

I have an issue where `attrs` is returning incorrect data to the render prop function. We rely on this to style our own custom arrow component.

The issue occurs under a two known circumstances:
1. the user triggers the tooltip extremely quickly after the DOM loads. In our case we hover the mouse right over the reference element and trigger almost immediately. The arrow will never appear anymore from here on out for any tooltip within the singleton. If the tooltip is triggered ~1s or later after the DOM loads, all arrows will work, even with different placements.
2. Sometimes the singleton wrapper/reference elements shift position on the page causing `attrs` to return `undefined` after previously having an arrow (hard to reproduce because it's very inconsistent)

A contrived example:
```
function Tooltip() {
  const [source, target] = useSingleton();

 const renderProp = () => (
    <Tippy
      render={attrs => (
        <Box {...attrs}>
          Hello
          <Arrow placement={attrs['data-placement']} data-popper-arrow="" />
        </Box>
      )}
    >
      <button>Reference</button>
    </Tippy>
  );

  return (
    <>
      <Tippy singleton={source} delay={500} />

      <Tippy content="Hello" singleton={target} placement='top' render={renderProp}>
        <button>Reference</button>
      </Tippy>
      <Tippy content="Bye" singleton={target} placement='bottom' render={renderProp}>
        <button>Reference</button>
      </Tippy>
    </>
  );
}
```

**Comment by atomiks** [comment]
The usage in the example seems incorrect. The render prop should be supplied to the source Tippy not the target ones.

**Comment by atomiks** [comment]
[Check the usage on the docs](https://github.com/atomiks/tippyjs-react#headless-singleton). This shouldn't occur if `render` is being passed to the source singleton, rather than the target ones.
