### ISSUE TITLE
should ensure the ref is a DOM node reference

### ISSUE THREAD

**Issue by gitforjing** [atomiks/tippyjs-react#320]
![image](https://user-images.githubusercontent.com/29487095/126314864-884b7a95-b7f4-4eb1-8795-0e32032c82de.png)
![image](https://user-images.githubusercontent.com/29487095/126315143-588c8073-e677-43f6-b83e-f3b8066e83ac.png)
![image](https://user-images.githubusercontent.com/29487095/126315554-c24b5283-8fea-4aa9-8fa3-3c6fd5717144.png)

Tippyjs only accept DOM node as a reference. If not, a exception will be throwed by funtion getArrayOfElements.

**Comment by atomiks** [comment]
TypeScript handles this.
