### ISSUE TITLE
Unnecessary div ? 

### ISSUE THREAD

**Issue by maxime4000** [atomiks/tippyjs-react#322]
Hi so one of our lib use tippyjs-react and I was writing some e2e test and I was wondering why there was 4 level of div with the fourth seem unnecessary ? I though it was our lib that was adding it but it seem like it's tippyjs. I look at the demo site and I was able to replicate of it. It look like .tippy-content is the container, but there is another unnamed container inside which doesn't do anything. I was able to use chrome devtools drag&drop of element and move button outside of the unnamed div, delete the div and everything was still working out. Maybe there is more to it than it appear, but it seem pretty much unnecessary to my point of view. Can't said if this issues should be move to tippyjs as the demo is using the react implementation, so I post it here. 

![image](https://user-images.githubusercontent.com/4070713/128049869-c38f5a82-e2fb-4186-8421-ab47643cfae9.png)

**Comment by atomiks** [comment]
It's the container node in which the React content is inserted into, which is created by this wrapper lib. It was easier than the alternative of using the `.tippy-content` node, IIRC
