### ISSUE TITLE
pointer-events: none is set although interactive prop is set to true

### ISSUE THREAD

**Issue by BorisL91** [atomiks/tippyjs-react#329]
I have a react tooltip component which uses `<TippyComponent />` from `@tippyjs/react`. 
The component is defined in a component library, and those components are used as a module across multiple projects.

The `interactive` prop of the component is set to `true` in the project the component was defined, meaning there is no `pointer-events: none` set on the component there.

Now the problem is that when using the component outside of the project it has `pointer-events: none`  set, making it impossible to use interactive elements on the tooltip.

An ugly workaround is overwriting the `pointer-events` property in each project with an `!important` rule. 

Obviously, the `interactive` prop doesn't seem to properly handle `pointer-events` in my case.

If anyone had this situation, I would be happy to hear what your potential workaround was. Thanks!

**Comment by KubaJastrz** [comment]
Can you double check the react devtools to see if interactive is actually set to true in the Tippy component?

It seems like your component structure is overriding it somehow to false, even though the outermost component sets it to true.

**Comment by BorisL91** [comment]
Thanks for the quick reply :)

The interactive prop is not set on the component when using it outside of the module. :(

Still can't figure out where would my component structure overwrite a prop to false if it's explicitly set as default to `true`.

**Comment by BorisL91** [comment]
Solved,  I had a Context Wrapper where the prop was missing. Thank you for your support! :)
