### ISSUE TITLE
'interactive: true' cutt of and faq solution not working

### ISSUE THREAD

**Issue by nataliarossini** [atomiks/tippyjs-react#337]
I'm using next.js for this app and I made a tippy interactive on the navbar,  it worked very well. However, I'm trying to do exactly the same but in this component which is a menu for mobile and when I try to make it interactive, it goes all over the place. I read the documentation but popperOptions haven't changed anything and appendTo: document.body do not work well with next.js

here's without interactive: true
<img width="423" alt="Screenshot 2021-10-29 at 16 17 07" src="https://user-images.githubusercontent.com/47406531/139461431-f513c693-51d9-4e0e-8b37-7d054ea3e5b1.png">

and here's what happens with interactive
<img width="179" alt="Screenshot 2021-10-29 at 16 18 08" src="https://user-images.githubusercontent.com/47406531/139461550-f00588ed-eba4-49f6-a307-0c818e5e38b0.png">

I'd really appreciate any help, thank you!

**Comment by atomiks** [comment]
`appendTo: () => document.body` is the default for non-interactive tippys so that should work correctly, assuming you're implementing some focus management for a11y.

**Comment by nataliarossini** [comment]
Thanks a lot
