### ISSUE TITLE
Headless Tippy Offset function called many times

### ISSUE THREAD

**Issue by getreworked** [atomiks/tippyjs-react#338]
I'm not sure if this applies to React Tippy or Popper itself... 

I need to add a bit of custom offset positioning so I'm using the `popperOptions` prop and passing in a modifier for offset with a function. What I'm noticing is that the function is called many times (once for each type of position and then a few more times). It's not re-rendering the actual Tippy component too many times, just calling the provided offset function an unnecessary amount of times.

Replication: https://codesandbox.io/s/crazy-galileo-2bfji?file=/src/App.js

**Comment by atomiks** [comment]
Popper's offset modifier calls your function for every possible placement, which it adds to `state.modifiersData.offset`. Tippy also calls popper's update function a second time on mount, which fixes issues with certain modifiers which change the size of the tippy.

**Comment by atomiks** [comment]
So it's not a bug, that's how Popper works, the operations are way faster than the DOM calculations performed by Popper anyways.
