### ISSUE TITLE
interactive doesn't seem to work when used with render

### ISSUE THREAD

**Issue by danr-za** [atomiks/tippyjs-react#339]
I am trying to use Tippy in headless mode together with a singleton.
However, when setting `interactive=true` on the source, it doesn't affect the target.
Even when passing `interactive` in overrides and specifying it in the target instances, it is still not interactive.
However, if I'll switch to using `content` instead of `render`, everything works as expected.

Hope I am missing something 🤔 

This is my code:

```tsx
import React from "react";
import Tippy, {useSingleton} from "@tippyjs/react/headless";
import "tippy.js/dist/tippy.css";

const Content = () => <button>Interact with me</button>

export function TippyTest() {
  const [source, target] = useSingleton()

  return <>
    <Tippy singleton={source} placement="bottom" interactive theme="dark" render={(attrs, content, instance) => {
      return <div {...attrs} style={{backgroundColor: '#ccc', padding: '10px'}}>
          {content}
        </div>
    }}/>

    <Tippy singleton={target} content={<Content/>}>
      <button>Tippy #1</button>
    </Tippy>

    <Tippy singleton={target} content={<Content/>}>
      <button>Tippy #2</button>
    </Tippy>
  </>
}
```

**Comment by atomiks** [comment]
It looks like `pointer-events: none;` is being added despite it being interactive.

This would force it off (although for every single tippy, interactive or not):

```css
[data-tippy-root] { 
  pointer-events: auto !important;
}
```

**Comment by danr-za** [comment]
Thanks for the quick response!

Apparently, tippy's state `isVisible` prop is set to `false` for some reason in `render` function. That causes the condition in `handleStyles` to add pointer-events:

https://github.com/atomiks/tippyjs/blob/master/src/createTippy.ts#L217-L221

Will be waiting for v7 🚀
