### ISSUE TITLE
getting `undefined` content in Tippy render prop

### ISSUE THREAD

**Issue by KutnerUri** [atomiks/tippyjs-react#341]
when using the render prop, I am getting `content === undefined`. example code:

```tsx
const content = 'hello';

<Tippy
        placement="bottom"
        interactive
        content={content}
        render={(attrs, content) => (
          <Card elevation="high" {...attrs} className={styles.extraComponentsPad}>
            {content} /* <-- is always undefined */
          </Card>
        )}
      >
        <span>▾</span>
      </Tippy>
```

I'm using `"@tippyjs/react": "4.2.0"`

**Comment by atomiks** [comment]
That property is only useful if you're using a singleton. Since `content` is in scope for you, it has no purpose in the use case provided

**Comment by KutnerUri** [comment]
@atomiks - this was a simplified example. What if I want to make a custom tooltip component?

```tsx
function CustomTooltip(props: TippyProps) {
 return <Tippy {...props} render={CustomRender} />
}

function CustomRender(attrs: AttrsType, content: ReactNode) {
  return (
    <Card elevation="high" {...attrs} className="customTooltip">
        {content}
    </Card>
  );
}
```

Are you suggesting doing something like this?
```tsx
function CustomTooltip(props: TippyProps) {
 return <Tippy {...props} render={(attrs) => CustomRender(attrs, props.content)} />
}
```

It does not seem good practice / coding-style to use the render function inline, and might mess with hot reloading.

**Comment by atomiks** [comment]
If you're concerned about that, you can `memo` the render function

**Comment by KutnerUri** [comment]
ok
