### ISSUE TITLE
How to use onclickoutside in tippy.5.2.1

### ISSUE THREAD

**Issue by karthikGcan** [atomiks/tippyjs-react#344]
I am using Angular 7 , there i am using  tippy 5.2.1 which is not having onoutsideclick props , but in 6.00 version onclickoutside available.

      onClickOutside: (instance, event) => {
        this.isOpen = false;
        instance.unmount();
      },
this above function not working tippy.js 5.2.1, Please tell me how to use onclickoutside in tippy.js 5.2.1 ,Please provide asap 
 see the below code

 configureTippyInstance() {
    this.tippyInstance.enable();
    this.tippyInstance.show();

    this.tippyInstance.setProps({
      trigger: 'manual',
      placement: 'right',
      arrow: false,
      interactive: true,
      appendTo: document.body,
      hideOnClick: false,
      onShow: (instance) => {
        hideAll({ exclude: instance });
      },
      onClickOutside: (instance, event) => {
        this.isOpen = false;
        instance.unmount();
      },
    });
  }

Thanks in Advance.

**Comment by atomiks** [comment]
You can't use it because it doesn't exist in 5.x. You need to upgrade to v6.
