### ISSUE TITLE
how do we change background color of tippy message box?

### ISSUE THREAD

**Issue by AyoCodess** [atomiks/tippyjs-react#345]
![Screenshot 2022-01-31 at 20 33 29](https://user-images.githubusercontent.com/72066389/151794566-a48b0d5d-5999-491f-b0f0-42edb11ac328.png)

Any ideas? Thanks

The only framework im using for styling is tailwind 3.0

**Comment by atomiks** [comment]
For Tailwind you'll want to render everything from scratch using Headless Tippy. Alternatively, you could apply Tailwind's classes via `classList` on the `.tippy-box` element — but I think this has problems with the JIT compiler (in prod some of these might get wiped away).

**Comment by AyoCodess** [comment]
Thanks James, can you show me an example with headless tippy? 


Kind regards,

Ayo Adesanya

**Comment by atomiks** [comment]
https://github.com/atomiks/tippyjs-react#headless-tippy

You'd just put Tailwind's classes on the element

`className="bg-gray-900 text-gray-100 p-4"`
