### ISSUE TITLE
Animations with styled-components and followCursor

### ISSUE THREAD

**Issue by miasa** [atomiks/tippyjs-react#349]
Styling a cursor following Tippy with styled-components causes class attribute change when cursor is moved. This attribute change causes keyframe animations to start from beginning each time cursor moves.

The class attribute change does not occur with default Tippy or with global classes added onMount.

Is there another way to use animations with styled-components?

[Codesandbox demo](https://codesandbox.io/s/tippyjs-react-styled-components-l52cef?file=/src/App.js)

**Comment by atomiks** [comment]
Have you tried with Headless Tippy? That's generally a better way to fully style everything with SC

**Comment by miasa** [comment]
I got it to work with Headless Tippy, I didn't realize headless was the preferred method with styled-components. Thanks!
