### ISSUE TITLE
Using reference title attribute for content + hiding default tooltip

### ISSUE THREAD

**Issue by ryne** [atomiks/tippyjs-react#350]
["Can I use the title attribute?" @ FAQ | Tippy.js](https://atomiks.github.io/tippyjs/v5/faq/#can-i-use-the-attribute)

I'm looking to mimic the same behavior found above, but am running into this issue when passing a function into the 'content' in order to handle pulling a title into the content and removal of the original title attribute:

`react-dom.development.js:67 Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.`

Is there an easy way to implement this logic?

**Comment by atomiks** [comment]
You can use one of the lifecycle methods, `onCreate()` should work. `onCreate={({reference}) => {remove it}}`
