### ISSUE TITLE
When I put large text, the box doesn't fill all

### ISSUE THREAD

**Issue by alclord** [atomiks/tippyjs-react#369]
Hello, I'm just starting in the dev world, and I'm having a hard time using the tooltip. When I put large text, the box doesn't fill all the way, and the line doesn't break. Leaving a part of the text "loose". How can I adjust this?

![Screenshot_1](https://user-images.githubusercontent.com/80472247/200644330-b9fa8272-81d8-4bbc-972b-79d80bdda21c.png)

**Comment by atomiks** [comment]
Looks like it needs `overflow-wrap: break-word;` CSS on the content. 

Increasing the `maxWidth` of the tippy and/or adding CSS styles to apply a `...` ellipsis when it will overflow to ensure it doesn't break over multiple lines is also possible.
