### ISSUE TITLE
Error in production, Tippy js not working after next js build

### ISSUE THREAD

**Issue by Naeem775** [atomiks/tippyjs-react#381]
Hi,

I really like @tippyjs/react and it works great in development, but as soon as i create nextjs build, whichever component is using tippy throw error in next js production.
Error Screen Image
![image](https://github.com/atomiks/tippyjs-react/assets/32215735/f9f4b963-ef5f-4785-88ec-d2ce0c449a35)

Console Error image
![image](https://github.com/atomiks/tippyjs-react/assets/32215735/310b597e-74d8-4eda-92af-4ed7705ca074)

@tippyjs/react  Version : 4.2.6
Next js Version : 13.4.12 

As soon as i remove tippy, everything works fine, how can i remove this error?

**Comment by Vishtar** [comment]
I also got an error during a build time (just React with ReactDOMServer.renderToString()):

> Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

```
import Tippy from '@tippyjs/react';

export const Tag = () => {
    const tooltipText = 'Lorem...'
    return <Tippy content={tooltipText} delay={100} className="tag-tooltip">
            <span>Lorem...</span>
        </Tippy>
}
```

@tippyjs/react: 4.2.6
react-dom: 18.2.0

**Comment by RobSchilderr** [comment]
Same issue here.

**Comment by atomiks** [comment]
See https://github.com/atomiks/tippyjs-react/issues/379#issuecomment-1678021213
